/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { GatewayHealthSnapshot } from 'dsh-gateway/client-types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$65766f666f72676547617465776179 {
    overview: () => Promise<RemoteResult<GatewayHealthSnapshot>>
  }
  interface TypertRemoteMap {
    'evoforgeGateway/overview': () => Promise<RemoteResult<GatewayHealthSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'evoforgeGateway': TypertRemoteNamespace$65766f666f72676547617465776179
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
