/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_evoforge_gateway_evoforgeGateway_approvePairing_parameter_0$schema = z.string()
const dsh_evoforge_gateway_evoforgeGateway_approvePairing_parameter_1$schema = z.string()
const dsh_evoforge_gateway_evoforgeGateway_approvePairing_parameter_2$schema = z.string()
const dsh_evoforge_gateway_evoforgeGateway_approvePairing_parameter_3$schema = z.string()
const dsh_evoforge_gateway_evoforgeGateway_approvePairing_result$schema = z.object({
  'routeId': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'sessionId': z.string().readonly(),
})
const dsh_evoforge_gateway_evoforgeGateway_approvePairingRequest_parameter_0$schema = z.string()
const dsh_evoforge_gateway_evoforgeGateway_approvePairingRequest_parameter_1$schema = z.string()
const dsh_evoforge_gateway_evoforgeGateway_approvePairingRequest_parameter_2$schema = z.string()
const dsh_evoforge_gateway_evoforgeGateway_approvePairingRequest_result$schema = z.object({
  'routeId': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'sessionId': z.string().readonly(),
})
const dsh_evoforge_gateway_evoforgeGateway_overview_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'observedAt': z.number().readonly(),
  'lifecycle': z.union([z.literal("starting"), z.literal("ready"), z.literal("stopping")]).readonly(),
  'routes': z.object({
  'total': z.number().readonly(),
  'liveSessions': z.number().readonly(),
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'adapter': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'sessionId': z.string().readonly(),
  'threadScoped': z.boolean().readonly(),
  'live': z.boolean().readonly(),
  'paired': z.boolean().readonly(),
})).readonly(),
}).readonly(),
  'ingress': z.object({
  'total': z.number().readonly(),
  'prepared': z.number().readonly(),
  'executing': z.number().readonly(),
  'settled': z.number().readonly(),
  'uncertain': z.number().readonly(),
}).readonly(),
  'transports': z.object({
  'registrations': z.number().readonly(),
  'connecting': z.number().readonly(),
  'ready': z.number().readonly(),
  'degraded': z.number().readonly(),
  'stopping': z.number().readonly(),
  'items': z.array(z.object({
  'adapter': z.string().readonly(),
  'kind': z.string().readonly(),
  'routeIds': z.array(z.string()).readonly(),
  'state': z.union([z.literal("ready"), z.literal("stopping"), z.literal("connecting"), z.literal("degraded")]).readonly(),
  'observedAt': z.number().readonly(),
  'connectedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'lastInboundAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'lastActivityAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'lastErrorAt': z.union([z.undefined(), z.number()]).readonly().optional(),
})).readonly(),
}).readonly(),
  'outbound': z.object({
  'registrations': z.number().readonly(),
  'scheduled': z.number().readonly(),
  'total': z.number().readonly(),
  'prepared': z.number().readonly(),
  'sending': z.number().readonly(),
  'retrying': z.number().readonly(),
  'delivered': z.number().readonly(),
  'uncertain': z.number().readonly(),
  'failed': z.number().readonly(),
  'last': z.union([z.undefined(), z.object({
  'id': z.string().readonly(),
  'routeId': z.string().readonly(),
  'kind': z.union([z.literal("turn"), z.literal("response"), z.literal("notice")]).readonly(),
  'status': z.union([z.literal("prepared"), z.literal("sending"), z.literal("retrying"), z.literal("delivered"), z.literal("uncertain"), z.literal("failed")]).readonly(),
  'attempts': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})
const dsh_evoforge_gateway_evoforgeGateway_pendingPairings_result$schema = z.array(z.object({
  'requestId': z.string().readonly(),
  'adapter': z.string().readonly(),
  'accountIdHash': z.string().readonly(),
  'createdAt': z.number().readonly(),
  'expiresAt': z.number().readonly(),
}))
const dsh_evoforge_gateway_evoforgeGateway_revokePairing_parameter_0$schema = z.string()
const dsh_evoforge_gateway_evoforgeGateway_revokePairing_result$schema = z.object({
  'routeId': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'sessionId': z.string().readonly(),
  'revokedAt': z.number().readonly(),
  'alreadyRevoked': z.boolean().readonly(),
})

export const TYPERT = {
  package: 'dsh-evoforge-gateway',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-evoforge-gateway#evoforgeGateway/approvePairing',
      service: 'evoforge.gatewayHealth',
      namespace: 'evoforgeGateway',
      method: 'approvePairing',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_code',
          wire: '_code',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evoforge-gateway#evoforgeGateway/approvePairing:_code',
            schema: dsh_evoforge_gateway_evoforgeGateway_approvePairing_parameter_0$schema,
          },
        },
        {
          name: '_adapter',
          wire: '_adapter',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evoforge-gateway#evoforgeGateway/approvePairing:_adapter',
            schema: dsh_evoforge_gateway_evoforgeGateway_approvePairing_parameter_1$schema,
          },
        },
        {
          name: '_workspaceId',
          wire: '_workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evoforge-gateway#evoforgeGateway/approvePairing:_workspaceId',
            schema: dsh_evoforge_gateway_evoforgeGateway_approvePairing_parameter_2$schema,
          },
        },
        {
          name: '_sessionId',
          wire: '_sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evoforge-gateway#evoforgeGateway/approvePairing:_sessionId',
            schema: dsh_evoforge_gateway_evoforgeGateway_approvePairing_parameter_3$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evoforge-gateway/client-types#GatewayPairingSessionApprovalReceipt',
        schema: dsh_evoforge_gateway_evoforgeGateway_approvePairing_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-gateway/src/gateway-remote.typert.ts","line":36,"column":3},
    },
    {
      id: 'dsh-evoforge-gateway#evoforgeGateway/approvePairingRequest',
      service: 'evoforge.gatewayHealth',
      namespace: 'evoforgeGateway',
      method: 'approvePairingRequest',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_requestId',
          wire: '_requestId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evoforge-gateway#evoforgeGateway/approvePairingRequest:_requestId',
            schema: dsh_evoforge_gateway_evoforgeGateway_approvePairingRequest_parameter_0$schema,
          },
        },
        {
          name: '_workspaceId',
          wire: '_workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evoforge-gateway#evoforgeGateway/approvePairingRequest:_workspaceId',
            schema: dsh_evoforge_gateway_evoforgeGateway_approvePairingRequest_parameter_1$schema,
          },
        },
        {
          name: '_sessionId',
          wire: '_sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evoforge-gateway#evoforgeGateway/approvePairingRequest:_sessionId',
            schema: dsh_evoforge_gateway_evoforgeGateway_approvePairingRequest_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evoforge-gateway/client-types#GatewayPairingSessionApprovalReceipt',
        schema: dsh_evoforge_gateway_evoforgeGateway_approvePairingRequest_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-gateway/src/gateway-remote.typert.ts","line":27,"column":3},
    },
    {
      id: 'dsh-evoforge-gateway#evoforgeGateway/overview',
      service: 'evoforge.gatewayHealth',
      namespace: 'evoforgeGateway',
      method: 'overview',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evoforge-gateway/client-types#GatewayHealthSnapshot',
        schema: dsh_evoforge_gateway_evoforgeGateway_overview_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-gateway/src/gateway-remote.typert.ts","line":17,"column":3},
    },
    {
      id: 'dsh-evoforge-gateway#evoforgeGateway/pendingPairings',
      service: 'evoforge.gatewayHealth',
      namespace: 'evoforgeGateway',
      method: 'pendingPairings',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evoforge-gateway#evoforgeGateway/pendingPairings:result',
        schema: dsh_evoforge_gateway_evoforgeGateway_pendingPairings_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-gateway/src/gateway-remote.typert.ts","line":22,"column":3},
    },
    {
      id: 'dsh-evoforge-gateway#evoforgeGateway/revokePairing',
      service: 'evoforge.gatewayHealth',
      namespace: 'evoforgeGateway',
      method: 'revokePairing',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_routeId',
          wire: '_routeId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evoforge-gateway#evoforgeGateway/revokePairing:_routeId',
            schema: dsh_evoforge_gateway_evoforgeGateway_revokePairing_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evoforge-gateway/client-types#GatewayPairingRevocationReceipt',
        schema: dsh_evoforge_gateway_evoforgeGateway_revokePairing_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-gateway/src/gateway-remote.typert.ts","line":46,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Generated-Remote adapter over the existing Gateway authority.",
        "summary": "Generated-Remote adapter over the existing Gateway authority.",
        "tags": [],
        "jsDoc": "/** Generated-Remote adapter over the existing Gateway authority. */",
        "key": "evoforge.gatewayHealth",
        "exportName": "GatewayRemoteService",
        "members": [
          {
            "kind": "method",
            "name": "overview",
            "signature": "overview(): Promise<GatewayHealthSnapshot>"
          },
          {
            "kind": "method",
            "name": "pendingPairings",
            "signature": "pendingPairings(): Promise<readonly GatewayPairingPendingRequest[]>"
          },
          {
            "kind": "method",
            "name": "approvePairingRequest",
            "signature": "approvePairingRequest( requestId: string, workspaceId: string, sessionId: string, ): Promise<GatewayPairingSessionApprovalReceipt>"
          },
          {
            "kind": "method",
            "name": "approvePairing",
            "signature": "approvePairing( code: string, adapter: string, workspaceId: string, sessionId: string, ): Promise<GatewayPairingSessionApprovalReceipt>"
          },
          {
            "kind": "method",
            "name": "revokePairing",
            "signature": "revokePairing(routeId: string): Promise<GatewayPairingRevocationReceipt>"
          }
        ],
        "types": [
          {
            "name": "GatewayHealthRoute",
            "declaration": "export interface GatewayHealthRoute {\n    readonly id: string;\n    readonly adapter: string;\n    readonly workspaceId: string;\n    readonly sessionId: string;\n    readonly threadScoped: boolean;\n    readonly live: boolean;\n    readonly paired: boolean;\n}"
          },
          {
            "name": "GatewayHealthSnapshot",
            "declaration": "export interface GatewayHealthSnapshot {\n    readonly schemaVersion: 1;\n    readonly observedAt: number;\n    readonly lifecycle: 'starting' | 'ready' | 'stopping';\n    readonly routes: { readonly total: number; readonly liveSessions: number; readonly items: readonly GatewayHealthRoute[]; };\n    readonly ingress: { readonly total: number; readonly prepared: number; readonly executing: number; readonly settled: number; readonly uncertain: number; };\n    readonly transports: GatewayTransportHealth;\n    readonly outbound: GatewayOutboundHealth;\n}"
          },
          {
            "name": "GatewayOutboundHealth",
            "declaration": "export interface GatewayOutboundHealth {\n    readonly registrations: number;\n    readonly scheduled: number;\n    readonly total: number;\n    readonly prepared: number;\n    readonly sending: number;\n    readonly retrying: number;\n    readonly delivered: number;\n    readonly uncertain: number;\n    readonly failed: number;\n    readonly last?: { readonly id: string; readonly routeId: string; readonly kind: GatewayOutboundRecord['kind']; readonly status: GatewayOutboundStatus; readonly attempts: number; readonly updatedAt: number; };\n}"
          },
          {
            "name": "GatewayOutboundRecord",
            "declaration": "export type GatewayOutboundRecord = z.infer<typeof outboundSchema>;"
          },
          {
            "name": "GatewayOutboundStatus",
            "declaration": "export type GatewayOutboundStatus = GatewayOutboundRecord['status'];"
          },
          {
            "name": "GatewayPairingPendingRequest",
            "declaration": "export interface GatewayPairingPendingRequest {\n    readonly requestId: string;\n    readonly adapter: string;\n    readonly accountIdHash: string;\n    readonly createdAt: number;\n    readonly expiresAt: number;\n}"
          },
          {
            "name": "GatewayPairingRevocation",
            "declaration": "export interface GatewayPairingRevocation {\n    readonly routeId: string;\n    readonly workspaceId: string;\n    readonly sessionId: string;\n    readonly revokedAt: number;\n    readonly alreadyRevoked: boolean;\n}"
          },
          {
            "name": "GatewayPairingRevocationReceipt",
            "declaration": "export type GatewayPairingRevocationReceipt = GatewayPairingRevocation;"
          },
          {
            "name": "GatewayPairingSessionApprovalReceipt",
            "declaration": "export interface GatewayPairingSessionApprovalReceipt {\n    readonly routeId: string;\n    readonly workspaceId: string;\n    readonly sessionId: string;\n}"
          },
          {
            "name": "GatewayTransportHealth",
            "declaration": "export interface GatewayTransportHealth {\n    readonly registrations: number;\n    readonly connecting: number;\n    readonly ready: number;\n    readonly degraded: number;\n    readonly stopping: number;\n    readonly items: readonly GatewayTransportHealthItem[];\n}"
          },
          {
            "name": "GatewayTransportHealthItem",
            "declaration": "export interface GatewayTransportHealthItem extends GatewayTransportObservation {\n    readonly adapter: string;\n    readonly kind: string;\n    readonly routeIds: readonly string[];\n}"
          },
          {
            "name": "GatewayTransportObservation",
            "declaration": "export interface GatewayTransportObservation {\n    readonly state: GatewayTransportState;\n    readonly observedAt: number;\n    readonly connectedAt?: number;\n    readonly lastInboundAt?: number;\n    readonly lastActivityAt?: number;\n    readonly lastErrorAt?: number;\n}"
          },
          {
            "name": "GatewayTransportState",
            "declaration": "export type GatewayTransportState = 'connecting' | 'ready' | 'degraded' | 'stopping';"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "Terminal outbound observation for optional long-term evidence projection.",
        "summary": "Terminal outbound observation for optional long-term evidence projection.",
        "tags": [],
        "jsDoc": "/** Terminal outbound observation for optional long-term evidence projection. */",
        "name": "evoforge/gateway/outbound",
        "signature": "'evoforge/gateway/outbound'(observation: GatewayOutboundObservation & { readonly workspaceId: string; }): void"
      },
      {
        "description": "Startup observation for inflight journal entries recovered after a prior interruption.",
        "summary": "Startup observation for inflight journal entries recovered after a prior interruption.",
        "tags": [],
        "jsDoc": "/** Startup observation for inflight journal entries recovered after a prior interruption. */",
        "name": "evoforge/gateway/recovery",
        "signature": "'evoforge/gateway/recovery'(observation: GatewayRecoveryObservation): void"
      }
    ],
    "objects": []
  },
}
