/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_gateway_evoforgeGateway_overview_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'observedAt': z.number().readonly(),
  'lifecycle': z.union([z.literal("starting"), z.literal("ready"), z.literal("stopping")]).readonly(),
  'routes': z.object({
  'total': z.number().readonly(),
  'liveSessions': z.number().readonly(),
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'adapter': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'sessionId': z.string().readonly(),
  'threadScoped': z.boolean().readonly(),
  'live': z.boolean().readonly(),
})).readonly(),
}).readonly(),
  'ingress': z.object({
  'total': z.number().readonly(),
  'prepared': z.number().readonly(),
  'executing': z.number().readonly(),
  'settled': z.number().readonly(),
  'uncertain': z.number().readonly(),
}).readonly(),
  'transports': z.object({
  'registrations': z.number().readonly(),
  'connecting': z.number().readonly(),
  'ready': z.number().readonly(),
  'degraded': z.number().readonly(),
  'stopping': z.number().readonly(),
  'items': z.array(z.object({
  'adapter': z.string().readonly(),
  'kind': z.string().readonly(),
  'routeIds': z.array(z.string()).readonly(),
  'state': z.union([z.literal("ready"), z.literal("stopping"), z.literal("connecting"), z.literal("degraded")]).readonly(),
  'observedAt': z.number().readonly(),
  'connectedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'lastActivityAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'lastErrorAt': z.union([z.undefined(), z.number()]).readonly().optional(),
})).readonly(),
}).readonly(),
  'outbound': z.object({
  'registrations': z.number().readonly(),
  'scheduled': z.number().readonly(),
  'total': z.number().readonly(),
  'prepared': z.number().readonly(),
  'sending': z.number().readonly(),
  'retrying': z.number().readonly(),
  'delivered': z.number().readonly(),
  'uncertain': z.number().readonly(),
  'failed': z.number().readonly(),
  'last': z.union([z.undefined(), z.object({
  'id': z.string().readonly(),
  'routeId': z.string().readonly(),
  'kind': z.union([z.literal("turn"), z.literal("response"), z.literal("notice")]).readonly(),
  'status': z.union([z.literal("prepared"), z.literal("sending"), z.literal("retrying"), z.literal("delivered"), z.literal("uncertain"), z.literal("failed")]).readonly(),
  'attempts': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})]).readonly().optional(),
}).readonly(),
})

export const TYPERT = {
  package: 'dsh-gateway',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-gateway#evoforgeGateway/overview',
      service: 'evoforge.gatewayHealth',
      namespace: 'evoforgeGateway',
      method: 'overview',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-gateway/client-types#GatewayHealthSnapshot',
        schema: dsh_gateway_evoforgeGateway_overview_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-gateway/src/gateway-remote.typert.ts","line":12,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Generated-Remote adapter over the existing Gateway authority.",
        "summary": "Generated-Remote adapter over the existing Gateway authority.",
        "tags": [],
        "jsDoc": "/** Generated-Remote adapter over the existing Gateway authority. */",
        "key": "evoforge.gatewayHealth",
        "exportName": "GatewayRemoteService",
        "members": [
          {
            "kind": "method",
            "name": "overview",
            "signature": "overview(): Promise<GatewayHealthSnapshot>"
          }
        ],
        "types": [
          {
            "name": "GatewayHealthRoute",
            "declaration": "export interface GatewayHealthRoute {\n    readonly id: string;\n    readonly adapter: string;\n    readonly workspaceId: string;\n    readonly sessionId: string;\n    readonly threadScoped: boolean;\n    readonly live: boolean;\n}"
          },
          {
            "name": "GatewayHealthSnapshot",
            "declaration": "export interface GatewayHealthSnapshot {\n    readonly schemaVersion: 1;\n    readonly observedAt: number;\n    readonly lifecycle: 'starting' | 'ready' | 'stopping';\n    readonly routes: { readonly total: number; readonly liveSessions: number; readonly items: readonly GatewayHealthRoute[]; };\n    readonly ingress: { readonly total: number; readonly prepared: number; readonly executing: number; readonly settled: number; readonly uncertain: number; };\n    readonly transports: GatewayTransportHealth;\n    readonly outbound: GatewayOutboundHealth;\n}"
          },
          {
            "name": "GatewayOutboundHealth",
            "declaration": "export interface GatewayOutboundHealth {\n    readonly registrations: number;\n    readonly scheduled: number;\n    readonly total: number;\n    readonly prepared: number;\n    readonly sending: number;\n    readonly retrying: number;\n    readonly delivered: number;\n    readonly uncertain: number;\n    readonly failed: number;\n    readonly last?: { readonly id: string; readonly routeId: string; readonly kind: GatewayOutboundRecord['kind']; readonly status: GatewayOutboundStatus; readonly attempts: number; readonly updatedAt: number; };\n}"
          },
          {
            "name": "GatewayOutboundRecord",
            "declaration": "export type GatewayOutboundRecord = z.infer<typeof outboundSchema>;"
          },
          {
            "name": "GatewayOutboundStatus",
            "declaration": "export type GatewayOutboundStatus = GatewayOutboundRecord['status'];"
          },
          {
            "name": "GatewayTransportHealth",
            "declaration": "export interface GatewayTransportHealth {\n    readonly registrations: number;\n    readonly connecting: number;\n    readonly ready: number;\n    readonly degraded: number;\n    readonly stopping: number;\n    readonly items: readonly GatewayTransportHealthItem[];\n}"
          },
          {
            "name": "GatewayTransportHealthItem",
            "declaration": "export interface GatewayTransportHealthItem extends GatewayTransportObservation {\n    readonly adapter: string;\n    readonly kind: string;\n    readonly routeIds: readonly string[];\n}"
          },
          {
            "name": "GatewayTransportObservation",
            "declaration": "export interface GatewayTransportObservation {\n    readonly state: GatewayTransportState;\n    readonly observedAt: number;\n    readonly connectedAt?: number;\n    readonly lastActivityAt?: number;\n    readonly lastErrorAt?: number;\n}"
          },
          {
            "name": "GatewayTransportState",
            "declaration": "export type GatewayTransportState = 'connecting' | 'ready' | 'degraded' | 'stopping';"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
