export const STYLE_ID = 'evoforge-feishu-v1'

export const cssText = `
.dsh-feishu-trigger{display:flex;align-items:center;justify-content:center;gap:8px;min-height:36px;padding:0 10px;border:0;border-radius:8px;background:transparent;color:var(--color-text-secondary,#666);cursor:pointer;font:inherit}.dsh-feishu-trigger:hover{background:var(--color-bg-hover,rgba(127,127,127,.1));color:var(--color-text,#202124)}
.dsh-feishu-panel{position:fixed;z-index:80;left:max(72px,calc((100vw - min(720px,calc(100vw - 32px)))/2));top:50%;transform:translateY(-50%);width:min(720px,calc(100vw - 32px));max-height:calc(100vh - 32px);overflow:auto;border:1px solid var(--color-border,#ddd);border-radius:16px;background:var(--color-bg,#fff);color:var(--color-text,#202124);box-shadow:0 20px 60px rgba(0,0,0,.22)}
.dsh-feishu-head{position:sticky;top:0;display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid var(--color-border,#ddd);background:inherit}.dsh-feishu-title{margin:0;font-size:18px}.dsh-feishu-close{width:34px;height:34px;border:0;border-radius:8px;background:transparent;color:inherit;font-size:24px;cursor:pointer}.dsh-feishu-close:hover{background:var(--color-bg-hover,rgba(127,127,127,.1))}
.dsh-feishu-body{display:grid;gap:18px;padding:20px}
.dsh-feishu-actions{display:flex;flex-wrap:wrap;gap:10px}.dsh-feishu-button{min-height:38px;padding:0 14px;border:1px solid var(--color-border,#ccc);border-radius:9px;background:var(--color-bg,#fff);color:inherit;cursor:pointer;font:inherit}.dsh-feishu-button:hover:not(:disabled){border-color:var(--color-primary,#4f6ef7);color:var(--color-primary,#3856d6)}.dsh-feishu-button:disabled{opacity:.55;cursor:not-allowed}.dsh-feishu-primary{border-color:var(--color-primary,#4f6ef7);background:var(--color-primary,#4f6ef7);color:#fff}.dsh-feishu-primary:hover:not(:disabled){color:#fff;filter:brightness(.96)}
.dsh-feishu-message{padding:11px 13px;border-radius:9px;background:var(--color-bg-subtle,rgba(127,127,127,.07));line-height:1.5}.dsh-feishu-error{background:rgba(190,40,40,.1);color:var(--color-danger,#a32626)}
.dsh-feishu-health-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.dsh-feishu-health-head h3,.dsh-feishu-health-routes h3{margin:0 0 6px;font-size:16px}.dsh-feishu-health-head p,.dsh-feishu-health-foot{margin:0;color:var(--color-text-secondary,#666);line-height:1.55}.dsh-feishu-health-status{flex:none;padding:5px 9px;border-radius:999px;background:rgba(42,145,82,.12);color:#19723d;font-size:12px;font-weight:700}.dsh-feishu-health-status.is-busy{background:rgba(45,105,210,.12);color:#275eb2}.dsh-feishu-health-status.is-attention,.dsh-feishu-health-status.is-degraded{background:rgba(190,90,25,.13);color:#96500f}.dsh-feishu-health-status.is-stopping{background:rgba(127,127,127,.14);color:var(--color-text-secondary,#666)}.dsh-feishu-health-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:0}.dsh-feishu-health-grid div{min-width:0;padding:12px;border-radius:10px;background:var(--color-bg-subtle,rgba(127,127,127,.07))}.dsh-feishu-health-grid dt{overflow:hidden;color:var(--color-text-secondary,#666);font-size:12px;text-overflow:ellipsis;white-space:nowrap}.dsh-feishu-health-grid dd{margin:5px 0 0;font-size:17px;font-weight:650;overflow-wrap:anywhere}.dsh-feishu-health-routes{display:grid;gap:8px}.dsh-feishu-health-route{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 12px;border:1px solid var(--color-border,#ddd);border-radius:9px}.dsh-feishu-health-route span{color:var(--color-text-secondary,#666);font-size:12px}.dsh-feishu-health-foot{font-size:12px}
.dsh-feishu-content{display:grid;gap:12px;padding:14px;border:1px solid var(--color-border,#ddd);border-radius:12px}.dsh-feishu-content-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.dsh-feishu-content-head h3{margin:0;font-size:16px}.dsh-feishu-content-status{padding:4px 8px;border-radius:999px;background:rgba(190,90,25,.13);color:#96500f;font-size:12px;font-weight:700}.dsh-feishu-content-status.is-ready{background:rgba(42,145,82,.12);color:#19723d}.dsh-feishu-content-status.is-disabled{background:rgba(127,127,127,.14);color:var(--color-text-secondary,#666)}.dsh-feishu-content-permissions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.dsh-feishu-content-permissions>div{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:9px 10px;border-radius:8px;background:var(--color-bg-subtle,rgba(127,127,127,.07));font-size:13px}.dsh-feishu-content-permissions strong{font-size:11px}.dsh-feishu-content-permissions .is-enabled{color:#19723d}.dsh-feishu-content-permissions .is-disabled{color:var(--color-text-secondary,#777)}.dsh-feishu-content-facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:0}.dsh-feishu-content-facts div{min-width:0}.dsh-feishu-content-facts dt{color:var(--color-text-secondary,#666);font-size:11px}.dsh-feishu-content-facts dd{margin:3px 0 0;font-size:13px;font-weight:650;overflow-wrap:anywhere}
@media(max-width:720px){.dsh-feishu-panel{left:12px;width:calc(100vw - 24px);max-height:calc(100vh - 24px)}.dsh-feishu-body{padding:16px}.dsh-feishu-actions{display:grid}.dsh-feishu-button{width:100%}.dsh-feishu-health-grid,.dsh-feishu-content-facts{grid-template-columns:repeat(2,minmax(0,1fr))}.dsh-feishu-health-head{display:grid}}
`
