export const STYLE_ID = 'evoforge-feishu-v1'

export const cssText = `
.dsh-feishu-trigger{display:flex;align-items:center;justify-content:center;gap:8px;min-height:36px;padding:0 10px;border:0;border-radius:8px;background:transparent;color:var(--color-text-secondary,#666);cursor:pointer;font:inherit}.dsh-feishu-trigger:hover{background:var(--color-bg-hover,rgba(127,127,127,.1));color:var(--color-text,#202124)}
.dsh-feishu-panel{position:fixed;z-index:80;left:max(72px,calc((100vw - min(720px,calc(100vw - 32px)))/2));top:50%;transform:translateY(-50%);width:min(720px,calc(100vw - 32px));max-height:calc(100vh - 32px);overflow:auto;border:1px solid var(--color-border,#ddd);border-radius:16px;background:var(--color-bg,#fff);color:var(--color-text,#202124);box-shadow:0 20px 60px rgba(0,0,0,.22)}
.dsh-feishu-head{position:sticky;top:0;display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid var(--color-border,#ddd);background:inherit}.dsh-feishu-title{margin:0;font-size:18px}.dsh-feishu-close{width:34px;height:34px;border:0;border-radius:8px;background:transparent;color:inherit;font-size:24px;cursor:pointer}.dsh-feishu-close:hover{background:var(--color-bg-hover,rgba(127,127,127,.1))}
.dsh-feishu-body{display:grid;gap:18px;padding:20px}.dsh-feishu-intro h3,.dsh-feishu-config h3{margin:0 0 6px;font-size:16px}.dsh-feishu-intro p,.dsh-feishu-config p{margin:0;color:var(--color-text-secondary,#666);line-height:1.55}.dsh-feishu-steps{display:grid;gap:8px;padding:14px;border-radius:12px;background:var(--color-bg-subtle,rgba(127,127,127,.07));color:var(--color-text-secondary,#555)}
.dsh-feishu-actions{display:flex;flex-wrap:wrap;gap:10px}.dsh-feishu-button{min-height:38px;padding:0 14px;border:1px solid var(--color-border,#ccc);border-radius:9px;background:var(--color-bg,#fff);color:inherit;cursor:pointer;font:inherit}.dsh-feishu-button:hover:not(:disabled){border-color:var(--color-primary,#4f6ef7);color:var(--color-primary,#3856d6)}.dsh-feishu-button:disabled{opacity:.55;cursor:not-allowed}.dsh-feishu-primary{border-color:var(--color-primary,#4f6ef7);background:var(--color-primary,#4f6ef7);color:#fff}.dsh-feishu-primary:hover:not(:disabled){color:#fff;filter:brightness(.96)}
.dsh-feishu-phrase{display:grid;gap:10px;padding:16px;border:1px solid color-mix(in srgb,var(--color-primary,#4f6ef7) 38%,transparent);border-radius:12px;background:color-mix(in srgb,var(--color-primary,#4f6ef7) 7%,transparent)}.dsh-feishu-label{font-size:13px;color:var(--color-text-secondary,#666)}.dsh-feishu-code{margin:0;overflow:auto;white-space:pre-wrap;word-break:break-word;font:600 14px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.dsh-feishu-countdown{font-variant-numeric:tabular-nums;color:var(--color-primary,#3856d6)}
.dsh-feishu-message{padding:11px 13px;border-radius:9px;background:var(--color-bg-subtle,rgba(127,127,127,.07));line-height:1.5}.dsh-feishu-error{background:rgba(190,40,40,.1);color:var(--color-danger,#a32626)}.dsh-feishu-config pre{max-height:300px;margin:12px 0;overflow:auto;padding:14px;border-radius:10px;background:var(--color-bg-subtle,#f5f5f5);white-space:pre;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}
@media(max-width:720px){.dsh-feishu-panel{left:12px;width:calc(100vw - 24px);max-height:calc(100vh - 24px)}.dsh-feishu-body{padding:16px}.dsh-feishu-actions{display:grid}.dsh-feishu-button{width:100%}}
`
