export const STYLE_ID = 'dsh-gateway-v1'

export const cssText = `
.dsh-gateway-trigger{display:flex;align-items:center;gap:.55rem;width:100%;padding:.55rem .75rem;border:0;border-radius:.65rem;background:transparent;color:inherit;cursor:pointer}.dsh-gateway-trigger:hover{background:color-mix(in srgb,currentColor 9%,transparent)}
.dsh-gateway-panel{position:fixed;left:1rem;bottom:1rem;z-index:70;width:min(34rem,calc(100vw - 2rem));max-height:calc(100vh - 2rem);overflow:auto;border:1px solid color-mix(in srgb,currentColor 15%,transparent);border-radius:1rem;background:var(--dsh-color-background,#111827);color:var(--dsh-color-foreground,#f8fafc);box-shadow:0 1.2rem 4rem #0008}
.dsh-gateway-head{display:flex;justify-content:space-between;gap:1rem;padding:1rem 1.1rem;border-bottom:1px solid color-mix(in srgb,currentColor 12%,transparent)}.dsh-gateway-head h2,.dsh-gateway-head p{margin:0}.dsh-gateway-head p{margin-top:.2rem;font-size:.82rem;opacity:.68}.dsh-gateway-close{border:0;background:transparent;color:inherit;font-size:1.5rem;cursor:pointer}
.dsh-gateway-body{display:grid;gap:.9rem;padding:1rem 1.1rem}.dsh-gateway-status{justify-self:start;padding:.25rem .55rem;border-radius:999px;background:#16a34a33;color:#86efac;font-size:.78rem;font-weight:700}.dsh-gateway-status.is-degraded,.dsh-gateway-pill.is-degraded{background:#dc262633;color:#fca5a5}.dsh-gateway-status.is-attention{background:#d9770633;color:#fdba74}.dsh-gateway-status.is-busy,.dsh-gateway-status.is-stopping{background:#2563eb33;color:#93c5fd}
.dsh-gateway-message{padding:.7rem;border-radius:.65rem;background:color-mix(in srgb,currentColor 7%,transparent)}.dsh-gateway-message.is-error{background:#dc262626;color:#fecaca}.dsh-gateway-summary{display:flex;flex-wrap:wrap;gap:.55rem 1rem;align-items:center}.dsh-gateway-summary span{opacity:.68}
.dsh-gateway-message.is-success{background:#16a34a26;color:#bbf7d0}.dsh-gateway-pairing{padding:.75rem;border:1px solid color-mix(in srgb,currentColor 12%,transparent);border-radius:.7rem}.dsh-gateway-pairing p,.dsh-gateway-pairing small{margin:0;opacity:.72}.dsh-gateway-pairing label{font-size:.78rem;font-weight:700}.dsh-gateway-pairing-row{display:flex;gap:.5rem}.dsh-gateway-pairing-row input{min-width:0;flex:1;padding:.55rem .65rem;border:1px solid color-mix(in srgb,currentColor 18%,transparent);border-radius:.55rem;background:color-mix(in srgb,currentColor 6%,transparent);color:inherit;font:inherit;letter-spacing:.08em;text-transform:uppercase}.dsh-gateway-pairing-row button{padding:.55rem .75rem;border:0;border-radius:.55rem;background:#16a34a;color:white;cursor:pointer}.dsh-gateway-pairing-row button:disabled{opacity:.5;cursor:not-allowed}
.dsh-gateway-section{display:grid;gap:.55rem}.dsh-gateway-section h3{margin:0;font-size:.9rem}.dsh-gateway-transport{display:grid;grid-template-columns:1fr auto;gap:.45rem .7rem;padding:.7rem;border:1px solid color-mix(in srgb,currentColor 11%,transparent);border-radius:.7rem}.dsh-gateway-transport>div:first-child{display:flex;gap:.5rem;align-items:center}.dsh-gateway-transport code{font-size:.76rem;opacity:.8}.dsh-gateway-pill{padding:.18rem .45rem;border-radius:999px;background:#16a34a26;color:#86efac;font-size:.72rem}.dsh-gateway-routes{grid-column:1/-1;display:flex;flex-wrap:wrap;gap:.35rem}
.dsh-gateway-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:.45rem;margin:0}.dsh-gateway-grid div{padding:.55rem;border-radius:.6rem;background:color-mix(in srgb,currentColor 6%,transparent);text-align:center}.dsh-gateway-grid dt{font-size:.7rem;opacity:.65}.dsh-gateway-grid dd{margin:.18rem 0 0;font-weight:700}.dsh-gateway-foot{margin:0;font-size:.75rem;opacity:.65}.dsh-gateway-refresh{justify-self:start;padding:.5rem .8rem;border:0;border-radius:.6rem;background:#2563eb;color:white;cursor:pointer}.dsh-gateway-refresh:disabled{opacity:.55;cursor:wait}
@media(max-width:520px){.dsh-gateway-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
`
