/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { FeishuCredentialReferences } from 'dsh-evoforge-feishu/client-types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$65766f666f726765466569736875 {
    references: () => Promise<RemoteResult<FeishuCredentialReferences>>
  }
  interface TypertRemoteMap {
    'evoforgeFeishu/references': () => Promise<RemoteResult<FeishuCredentialReferences>>
  }
  interface TypertRemoteNamespaceMap {
    'evoforgeFeishu': TypertRemoteNamespace$65766f666f726765466569736875
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
