/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_evoforge_feishu_evoforgeFeishu_references_result$schema = z.object({
  'appIdRef': z.string().readonly(),
  'appSecretRef': z.string().readonly(),
})

export const TYPERT = {
  package: 'dsh-evoforge-feishu',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-evoforge-feishu#evoforgeFeishu/references',
      service: 'evoforge.feishuCredentials',
      namespace: 'evoforgeFeishu',
      method: 'references',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evoforge-feishu/client-types#FeishuCredentialReferences',
        schema: dsh_evoforge_feishu_evoforgeFeishu_references_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-feishu/src/feishu-credentials-remote.typert.ts","line":11,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
