/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { EvolutionActionReceipt, EvolutionOverview, EvolutionReviewDetail } from 'dsh-evolve/client'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$65766f666f72676545766f6c7574696f6e {
    approveReview: (id: string, note: string) => Promise<RemoteResult<EvolutionActionReceipt>>
    overview: () => Promise<RemoteResult<EvolutionOverview>>
    pause: () => Promise<RemoteResult<EvolutionActionReceipt>>
    promote: (generationId: string) => Promise<RemoteResult<EvolutionActionReceipt>>
    rejectReview: (id: string, note: string) => Promise<RemoteResult<EvolutionActionReceipt>>
    resume: () => Promise<RemoteResult<EvolutionActionReceipt>>
    review: (id: string) => Promise<RemoteResult<EvolutionReviewDetail>>
    rollback: () => Promise<RemoteResult<EvolutionActionReceipt>>
    startFeedbackShadow: (signalId: string, targetId: string) => Promise<RemoteResult<EvolutionActionReceipt>>
  }
  interface TypertRemoteMap {
    'evoforgeEvolution/approveReview': (id: string, note: string) => Promise<RemoteResult<EvolutionActionReceipt>>
    'evoforgeEvolution/overview': () => Promise<RemoteResult<EvolutionOverview>>
    'evoforgeEvolution/pause': () => Promise<RemoteResult<EvolutionActionReceipt>>
    'evoforgeEvolution/promote': (generationId: string) => Promise<RemoteResult<EvolutionActionReceipt>>
    'evoforgeEvolution/rejectReview': (id: string, note: string) => Promise<RemoteResult<EvolutionActionReceipt>>
    'evoforgeEvolution/resume': () => Promise<RemoteResult<EvolutionActionReceipt>>
    'evoforgeEvolution/review': (id: string) => Promise<RemoteResult<EvolutionReviewDetail>>
    'evoforgeEvolution/rollback': () => Promise<RemoteResult<EvolutionActionReceipt>>
    'evoforgeEvolution/startFeedbackShadow': (signalId: string, targetId: string) => Promise<RemoteResult<EvolutionActionReceipt>>
  }
  interface TypertRemoteNamespaceMap {
    'evoforgeEvolution': TypertRemoteNamespace$65766f666f72676545766f6c7574696f6e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
