/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_evolve_evoforgeEvolution_approveReview_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_approveReview_parameter_1$schema = z.string()
const dsh_evolve_evoforgeEvolution_approveReview_parameter_2$schema = z.string()
const dsh_evolve_evoforgeEvolution_approveReview_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'workspaceId': z.string().readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_overview_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_overview_parameter_1$schema = z.union([z.undefined(), z.string()])
const dsh_evolve_evoforgeEvolution_overview_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'workspaceId': z.string().readonly(),
  'active': z.union([z.undefined(), z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'rollbackTargetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'createdAt': z.number().readonly(),
  'evaluatorVersion': z.string().readonly(),
  'policyVersion': z.string().readonly(),
  'artifacts': z.array(z.object({
  'kind': z.union([z.literal("skill"), z.literal("skill-bundle")]).readonly(),
  'name': z.string().readonly(),
  'gitCommit': z.union([z.undefined(), z.string()]).readonly().optional(),
  'artifactDigest': z.union([z.undefined(), z.string()]).readonly().optional(),
  'treeHash': z.string().readonly(),
  'lineage': z.union([z.undefined(), z.object({
  'kind': z.literal("internal-skill-candidate-lineage-v3").readonly(),
  'candidateId': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'opportunityId': z.string().readonly(),
  'evaluationEvidenceId': z.string().readonly(),
  'policyId': z.string().readonly(),
  'versionKind': z.literal("experience-authored-bundle-v1").readonly(),
  'contentHash': z.string().readonly(),
  'candidateTreeHash': z.string().readonly(),
  'admissionId': z.string().readonly(),
  'evaluationEnvelopeId': z.string().readonly(),
  'releaseAuthority': z.literal("none").readonly(),
})]).readonly().optional(),
})).readonly(),
})]).readonly().optional(),
  'recovery': z.object({
  'available': z.boolean().readonly(),
  'paused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
  'capabilityMap': z.union([z.undefined(), z.object({
  'status': z.union([z.literal("unobserved"), z.literal("complete"), z.literal("incomplete")]).readonly(),
  'catalogHash': z.union([z.undefined(), z.string()]).readonly().optional(),
  'capabilities': z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'source': z.string().readonly(),
  'provider': z.string().readonly(),
  'scope': z.literal("workspace-session").readonly(),
  'invocation': z.object({
  'model': z.boolean().readonly(),
  'user': z.boolean().readonly(),
}).readonly(),
  'versionKind': z.union([z.literal("provider-managed"), z.literal("evolved-tree")]).readonly(),
  'version': z.union([z.undefined(), z.string()]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'route': z.union([z.literal("available"), z.literal("model-selected"), z.literal("user-selected")]).readonly(),
})).readonly(),
})]).readonly().optional(),
  'capabilityGaps': z.union([z.undefined(), z.object({
  'confirmedCount': z.number().readonly(),
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'observedAt': z.number().readonly(),
  'requestedSkill': z.string().readonly(),
  'catalogHash': z.string().readonly(),
  'catalogSize': z.number().readonly(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'goal': z.union([z.undefined(), z.object({
  'id': z.string().readonly(),
  'revision': z.number().readonly(),
  'objective': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
  'status': z.literal("confirmed").readonly(),
  'evidence': z.union([z.object({
  'kind': z.literal("native-skill-miss").readonly(),
  'catalog': z.literal("complete").readonly(),
  'routing': z.literal("requested-skill-absent").readonly(),
  'providers': z.literal("settled").readonly(),
}), z.object({
  'kind': z.literal("model-declared-skill-gap").readonly(),
  'catalog': z.literal("complete").readonly(),
  'routing': z.literal("model-declared-no-applicable-skill").readonly(),
  'providers': z.literal("settled").readonly(),
})]).readonly(),
})).readonly(),
})]).readonly().optional(),
  'skillOpportunities': z.union([z.undefined(), z.object({
  'eligibleCount': z.number().readonly(),
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'skillName': z.string().readonly(),
  'gapIds': z.array(z.string()).readonly(),
  'goalIds': z.array(z.string()).readonly(),
  'gapCount': z.number().readonly(),
  'goalCount': z.number().readonly(),
  'firstObservedAt': z.number().readonly(),
  'lastObservedAt': z.number().readonly(),
  'evidence': z.object({
  'kind': z.literal("internal-experience-v3").readonly(),
  'eligibilityBasis': z.literal("two-or-more-distinct-goals").readonly(),
  'correctionSignals': z.object({
  'association': z.literal("exact-durable-skill-invocation").readonly(),
  'count': z.number().readonly(),
  'goalCount': z.number().readonly(),
  'ids': z.array(z.string()).readonly(),
  'referencesTruncated': z.boolean().readonly(),
}).readonly(),
  'deliveryOutcomes': z.object({
  'association': z.literal("same-goal-single-skill-gap").readonly(),
  'total': z.number().readonly(),
  'passed': z.number().readonly(),
  'failed': z.number().readonly(),
  'unknown': z.number().readonly(),
  'ids': z.array(z.string()).readonly(),
  'referencesTruncated': z.boolean().readonly(),
}).readonly(),
  'causalClaim': z.literal("none").readonly(),
}).readonly(),
  'evaluationReadiness': z.union([z.object({
  'status': z.union([z.literal("ready-to-seal"), z.literal("sealed")]).readonly(),
  'evidenceId': z.string().readonly(),
  'observedGoalCount': z.number().readonly(),
  'authoringGoalCount': z.number().readonly(),
  'admissionGoalCount': z.number().readonly(),
  'holdoutGoalCount': z.number().readonly(),
  'retentionGoalCount': z.number().readonly(),
  'proposerCanReadProtectedSamples': z.literal(false).readonly(),
  'releaseAuthority': z.literal("none").readonly(),
}), z.object({
  'status': z.literal("waiting").readonly(),
  'reason': z.literal("fewer-than-four-independent-goals").readonly(),
  'observedGoalCount': z.number().readonly(),
  'requiredGoalCount': z.literal(4).readonly(),
  'releaseAuthority': z.literal("none").readonly(),
}), z.object({
  'status': z.literal("unavailable").readonly(),
  'reason': z.literal("governance-policy-unavailable").readonly(),
  'observedGoalCount': z.number().readonly(),
  'releaseAuthority': z.literal("none").readonly(),
}), z.object({
  'status': z.literal("invalid").readonly(),
  'reason': z.literal("opportunity-evidence-invalid").readonly(),
  'observedGoalCount': z.number().readonly(),
  'releaseAuthority': z.literal("none").readonly(),
})]).readonly(),
  'status': z.literal("eligible-for-authoring").readonly(),
  'releaseAuthority': z.literal("none").readonly(),
})).readonly(),
})]).readonly().optional(),
  'skillImprovementOpportunities': z.union([z.undefined(), z.object({
  'waitingCount': z.number().readonly(),
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'skillName': z.string().readonly(),
  'invocationContentHash': z.string().readonly(),
  'feedbackSignalIds': z.array(z.string()).readonly(),
  'goalIds': z.array(z.string()).readonly(),
  'signalCount': z.number().readonly(),
  'goalCount': z.number().readonly(),
  'firstObservedAt': z.number().readonly(),
  'lastObservedAt': z.number().readonly(),
  'evidence': z.object({
  'kind': z.literal("internal-exact-skill-corrections-v1").readonly(),
  'association': z.literal("exact-durable-skill-invocation-content").readonly(),
  'eligibilityBasis': z.literal("two-or-more-distinct-goals-same-invocation-content").readonly(),
  'referencesTruncated': z.boolean().readonly(),
  'causalClaim': z.literal("none").readonly(),
}).readonly(),
  'status': z.literal("waiting-for-baseline-bundle").readonly(),
  'releaseAuthority': z.literal("none").readonly(),
})).readonly(),
})]).readonly().optional(),
  'skillCandidates': z.union([z.undefined(), z.object({
  'quarantinedCount': z.number().readonly(),
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'createdAt': z.number().readonly(),
  'skillName': z.string().readonly(),
  'description': z.string().readonly(),
  'opportunity': z.object({
  'kind': z.literal("internal-experience-v1").readonly(),
  'id': z.string().readonly(),
  'gapIds': z.array(z.string()).readonly(),
  'goalCount': z.number().readonly(),
}).readonly(),
  'authorship': z.object({
  'kind': z.literal("bounded-model-authoring-v1").readonly(),
  'policyId': z.string().readonly(),
  'modelIdentityHash': z.string().readonly(),
  'evaluationEvidenceId': z.string().readonly(),
  'inputDigest': z.string().readonly(),
}).readonly(),
  'scope': z.literal("workspace").readonly(),
  'version': z.object({
  'kind': z.literal("experience-authored-bundle-v1").readonly(),
  'artifactDigest': z.string().readonly(),
  'treeHash': z.string().readonly(),
}).readonly(),
  'contentHash': z.string().readonly(),
  'package': z.object({
  'path': z.string().readonly(),
  'fileCount': z.number().readonly(),
  'totalBytes': z.number().readonly(),
  'hasScripts': z.boolean().readonly(),
  'hasReferences': z.boolean().readonly(),
}).readonly(),
  'permissions': z.object({
  'declared': z.boolean().readonly(),
  'executableContent': z.boolean().readonly(),
  'externalEffects': z.literal("unknown").readonly(),
}).readonly(),
  'license': z.union([z.undefined(), z.object({
  'status': z.literal("declared").readonly(),
  'value': z.string().readonly(),
}), z.object({
  'status': z.literal("unknown").readonly(),
})]).readonly().optional(),
  'safety': z.object({
  'status': z.literal("quarantined").readonly(),
  'checks': z.array(z.object({
  'name': z.union([z.literal("artifact-digest-integrity"), z.literal("regular-files-only"), z.literal("skill-identity"), z.literal("effect-review")]).readonly(),
  'status': z.union([z.literal("passed"), z.literal("required")]).readonly(),
})).readonly(),
}).readonly(),
  'lifecycle': z.literal("inactive").readonly(),
  'verification': z.literal("unevaluated").readonly(),
  'execution': z.literal("never").readonly(),
})).readonly(),
})]).readonly().optional(),
  'slowLoopAuthoring': z.union([z.undefined(), z.object({
  'configuredPolicyCount': z.number().readonly(),
  'warningCount': z.number().readonly(),
  'runs': z.array(z.object({
  'id': z.string().readonly(),
  'targetId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'opportunityId': z.string().readonly(),
  'gapCount': z.number().readonly(),
  'goalCount': z.number().readonly(),
  'phase': z.union([z.literal("incomplete"), z.literal("prepared"), z.literal("budget-deferred"), z.literal("cancelled"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("candidate-ready")]).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'modelCalls': z.union([z.literal(0), z.literal(1)]).readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'candidateId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'retryAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'releaseAuthority': z.literal("none").readonly(),
})).readonly(),
})]).readonly().optional(),
  'skillEvaluationGovernance': z.union([z.undefined(), z.object({
  'configuredPolicyCount': z.number().readonly(),
  'warningCount': z.number().readonly(),
  'runs': z.array(z.object({
  'id': z.string().readonly(),
  'policyId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'opportunityId': z.string().readonly(),
  'evaluationEvidenceId': z.string().readonly(),
  'phase': z.union([z.literal("incomplete"), z.literal("prepared"), z.literal("budget-deferred"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("admission-ready"), z.literal("holdout-ready"), z.literal("authored"), z.literal("ready")]).readonly(),
  'pendingRole': z.union([z.undefined(), z.literal("admission"), z.literal("holdout"), z.literal("retention")]).readonly().optional(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'modelCalls': z.number().readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'retentionIncluded': z.boolean().readonly(),
  'retryAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'failure': z.union([z.undefined(), z.literal("paid-authoring-uncertain"), z.literal("admission-calibration-failed"), z.literal("holdout-calibration-failed"), z.literal("retention-calibration-failed"), z.literal("governance-incomplete")]).readonly().optional(),
  'releaseAuthority': z.literal("none").readonly(),
})).readonly(),
})]).readonly().optional(),
  'skillAdmission': z.union([z.undefined(), z.object({
  'configuredPolicyCount': z.number().readonly(),
  'warningCount': z.number().readonly(),
  'results': z.array(z.object({
  'id': z.string().readonly(),
  'candidateId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'status': z.union([z.literal("incomplete"), z.literal("abstained"), z.literal("protected"), z.literal("rejected"), z.literal("review"), z.literal("qualified-for-shadow")]).readonly(),
  'reasons': z.array(z.union([z.literal("no-current-evaluation-envelope"), z.literal("candidate-has-executable-content"), z.literal("candidate-is-not-instruction-only"), z.literal("baseline-identity-mismatch"), z.literal("case-pack-identity-mismatch"), z.literal("assembled-evaluator-not-governance-separated"), z.literal("case-pack-calibration-failed"), z.literal("candidate-failed-admission"), z.literal("baseline-already-passes"), z.literal("candidate-improves-deterministic-admission"), z.literal("governance-input-mutated"), z.literal("governance-roots-overlap"), z.literal("evaluation-failed")])).readonly(),
  'envelopeId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'releaseAuthority': z.literal("none").readonly(),
  'evidence': z.union([z.undefined(), z.object({
  'baseline': z.union([z.literal("pass"), z.literal("fail")]).readonly(),
  'candidate': z.union([z.literal("pass"), z.literal("fail")]).readonly(),
  'calibrationPassed': z.boolean().readonly(),
  'candidateExecuted': z.literal(false).readonly(),
  'evaluatorClass': z.literal("deterministic-filesystem").readonly(),
  'trialCount': z.literal(4).readonly(),
})]).readonly().optional(),
})).readonly(),
})]).readonly().optional(),
  'skillEvaluationRuns': z.union([z.undefined(), z.object({
  'configuredRetentionRootCount': z.number().readonly(),
  'warningCount': z.number().readonly(),
  'items': z.array(z.object({
  'candidateId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'lineage': z.object({
  'kind': z.literal("internal-skill-candidate-lineage-v3").readonly(),
  'candidateId': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'opportunityId': z.string().readonly(),
  'evaluationEvidenceId': z.string().readonly(),
  'policyId': z.string().readonly(),
  'versionKind': z.literal("experience-authored-bundle-v1").readonly(),
  'contentHash': z.string().readonly(),
  'candidateTreeHash': z.string().readonly(),
  'admissionId': z.string().readonly(),
  'evaluationEnvelopeId': z.string().readonly(),
  'releaseAuthority': z.literal("none").readonly(),
}).readonly(),
  'shadow': z.object({
  'runId': z.string().readonly(),
  'status': z.literal("complete").readonly(),
  'recommendation': z.union([z.literal("review"), z.literal("promote")]).readonly(),
  'cases': z.array(z.object({
  'id': z.string().readonly(),
  'baseline': z.union([z.literal("incomplete"), z.literal("pass"), z.literal("fail")]).readonly(),
  'candidate': z.union([z.literal("incomplete"), z.literal("pass"), z.literal("fail")]).readonly(),
  'passedChecks': z.number().readonly(),
  'totalChecks': z.number().readonly(),
})).readonly(),
  'cost': z.object({
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'trialCount': z.number().readonly(),
}).readonly(),
  'compositionStable': z.boolean().readonly(),
  'startedAt': z.string().readonly(),
}).readonly(),
  'retention': z.union([z.undefined(), z.object({
  'id': z.string().readonly(),
  'status': z.union([z.literal("incomplete"), z.literal("prepared"), z.literal("retained"), z.literal("regressed")]).readonly(),
  'reason': z.union([z.undefined(), z.literal("retention-calibration-failed"), z.literal("no-independent-retention-case"), z.literal("shadow-not-complete"), z.literal("shadow-not-promotable"), z.literal("retention-trial-failed"), z.literal("retention-input-mutated"), z.literal("retention-not-assembled"), z.literal("prior-case-baseline-failed"), z.literal("non-target-composition-changed"), z.literal("candidate-regressed-prior-case"), z.literal("candidate-retained-prior-case")]).readonly().optional(),
  'startedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
  'finishedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
  'evidence': z.union([z.undefined(), z.object({
  'baseline': z.union([z.literal("pass"), z.literal("fail")]).readonly(),
  'candidate': z.union([z.literal("pass"), z.literal("fail")]).readonly(),
  'calibrationPassed': z.boolean().readonly(),
  'compositionStable': z.boolean().readonly(),
  'proposerCalls': z.literal(0).readonly(),
  'trialCount': z.literal(4).readonly(),
  'modelCalls': z.union([z.undefined(), z.object({
  'baseline': z.number().readonly(),
  'candidate': z.number().readonly(),
})]).readonly().optional(),
  'usage': z.union([z.undefined(), z.object({
  'baseline': z.object({
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
  'reasoningTokens': z.number().readonly(),
}).readonly(),
  'candidate': z.object({
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
  'reasoningTokens': z.number().readonly(),
}).readonly(),
})]).readonly().optional(),
})]).readonly().optional(),
  'releaseAuthority': z.literal("none").readonly(),
})]).readonly().optional(),
  'releaseAuthority': z.literal("none").readonly(),
})).readonly(),
})]).readonly().optional(),
  'deliveryOutcomes': z.union([z.undefined(), z.object({
  'all': z.object({
  'total': z.number().readonly(),
  'passed': z.number().readonly(),
  'failed': z.number().readonly(),
  'unknown': z.number().readonly(),
}).readonly(),
  'selected': z.object({
  'total': z.number().readonly(),
  'passed': z.number().readonly(),
  'failed': z.number().readonly(),
  'unknown': z.number().readonly(),
}).readonly(),
  'baseline': z.union([z.undefined(), z.object({
  'total': z.number().readonly(),
  'passed': z.number().readonly(),
  'failed': z.number().readonly(),
  'unknown': z.number().readonly(),
})]).readonly().optional(),
  'metrics': z.object({
  'all': z.object({
  'measured': z.number().readonly(),
  'unmeasured': z.number().readonly(),
  'attributedTurns': z.number().readonly(),
  'closedSteps': z.number().readonly(),
  'activeWallMs': z.number().readonly(),
  'providerUsage': z.object({
  'uncachedInputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
}).readonly(),
  'latency': z.object({
  'llmMs': z.number().readonly(),
  'toolMs': z.number().readonly(),
  'ttftMs': z.number().readonly(),
  'ttftSteps': z.number().readonly(),
  'decodeMs': z.number().readonly(),
  'decodeTokens': z.number().readonly(),
}).readonly(),
  'monetaryCost': z.object({
  'status': z.literal("unavailable").readonly(),
  'reason': z.literal("provider-price-not-projected").readonly(),
}).readonly(),
}).readonly(),
  'selected': z.object({
  'measured': z.number().readonly(),
  'unmeasured': z.number().readonly(),
  'attributedTurns': z.number().readonly(),
  'closedSteps': z.number().readonly(),
  'activeWallMs': z.number().readonly(),
  'providerUsage': z.object({
  'uncachedInputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
}).readonly(),
  'latency': z.object({
  'llmMs': z.number().readonly(),
  'toolMs': z.number().readonly(),
  'ttftMs': z.number().readonly(),
  'ttftSteps': z.number().readonly(),
  'decodeMs': z.number().readonly(),
  'decodeTokens': z.number().readonly(),
}).readonly(),
  'monetaryCost': z.object({
  'status': z.literal("unavailable").readonly(),
  'reason': z.literal("provider-price-not-projected").readonly(),
}).readonly(),
}).readonly(),
  'baseline': z.union([z.undefined(), z.object({
  'measured': z.number().readonly(),
  'unmeasured': z.number().readonly(),
  'attributedTurns': z.number().readonly(),
  'closedSteps': z.number().readonly(),
  'activeWallMs': z.number().readonly(),
  'providerUsage': z.object({
  'uncachedInputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
}).readonly(),
  'latency': z.object({
  'llmMs': z.number().readonly(),
  'toolMs': z.number().readonly(),
  'ttftMs': z.number().readonly(),
  'ttftSteps': z.number().readonly(),
  'decodeMs': z.number().readonly(),
  'decodeTokens': z.number().readonly(),
}).readonly(),
  'monetaryCost': z.object({
  'status': z.literal("unavailable").readonly(),
  'reason': z.literal("provider-price-not-projected").readonly(),
}).readonly(),
})]).readonly().optional(),
  'recent': z.array(z.object({
  'outcomeId': z.string().readonly(),
  'observedAt': z.number().readonly(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.literal("unknown"), z.literal("passed"), z.literal("failed")]).readonly(),
  'goal': z.object({
  'id': z.string().readonly(),
  'revision': z.number().readonly(),
}).readonly(),
  'metrics': z.object({
  'schemaVersion': z.literal(1).readonly(),
  'source': z.literal("dsh-session-projections").readonly(),
  'goalId': z.string().readonly(),
  'throughEventSeq': z.number().readonly(),
  'attributedTurns': z.number().readonly(),
  'closedSteps': z.number().readonly(),
  'activeWallMs': z.number().readonly(),
  'providerUsage': z.object({
  'uncachedInputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'cacheReadTokens': z.number().readonly(),
  'cacheWriteTokens': z.number().readonly(),
}).readonly(),
  'latency': z.object({
  'llmMs': z.number().readonly(),
  'toolMs': z.number().readonly(),
  'ttftMs': z.number().readonly(),
  'ttftSteps': z.number().readonly(),
  'decodeMs': z.number().readonly(),
  'decodeTokens': z.number().readonly(),
}).readonly(),
  'monetaryCost': z.object({
  'status': z.literal("unavailable").readonly(),
  'reason': z.literal("provider-price-not-projected").readonly(),
}).readonly(),
}).readonly(),
})).readonly(),
}).readonly(),
})]).readonly().optional(),
  'feedbackSignals': z.union([z.undefined(), z.object({
  'all': z.number().readonly(),
  'selected': z.number().readonly(),
})]).readonly().optional(),
  'reviews': z.object({
  'available': z.boolean().readonly(),
  'pendingCount': z.number().readonly(),
  'actionableCount': z.number().readonly(),
  'warningCount': z.number().readonly(),
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'status': z.union([z.literal("rejected"), z.literal("pending"), z.literal("approved")]).readonly(),
  'recommendation': z.union([z.literal("review"), z.literal("promote")]).readonly(),
  'skillName': z.string().readonly(),
  'claim': z.string().readonly(),
  'changedFiles': z.array(z.string()).readonly(),
  'candidateTreeHash': z.string().readonly(),
  'lineage': z.union([z.undefined(), z.object({
  'kind': z.literal("internal-skill-candidate-lineage-v3").readonly(),
  'candidateId': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'opportunityId': z.string().readonly(),
  'evaluationEvidenceId': z.string().readonly(),
  'policyId': z.string().readonly(),
  'versionKind': z.literal("experience-authored-bundle-v1").readonly(),
  'contentHash': z.string().readonly(),
  'candidateTreeHash': z.string().readonly(),
  'admissionId': z.string().readonly(),
  'evaluationEnvelopeId': z.string().readonly(),
  'releaseAuthority': z.literal("none").readonly(),
})]).readonly().optional(),
  'cases': z.array(z.object({
  'id': z.string().readonly(),
  'baseline': z.union([z.literal("incomplete"), z.literal("pass"), z.literal("fail")]).readonly(),
  'candidate': z.union([z.literal("incomplete"), z.literal("pass"), z.literal("fail")]).readonly(),
  'passedChecks': z.number().readonly(),
  'totalChecks': z.number().readonly(),
})).readonly(),
  'cost': z.object({
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'trialCount': z.number().readonly(),
}).readonly(),
  'reasons': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'evaluatorVersion': z.string().readonly(),
  'compositionFingerprint': z.string().readonly(),
  'compositionStable': z.boolean().readonly(),
  'startedAt': z.string().readonly(),
  'decisionActor': z.union([z.undefined(), z.literal("human"), z.literal("auto-clear-instruction-v1")]).readonly().optional(),
  'decisionNote': z.union([z.undefined(), z.string()]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activatedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'inactiveGenerations': z.array(z.object({
  'workspaceId': z.string().readonly(),
  'generationId': z.string().readonly(),
  'reviewId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'lineage': z.union([z.undefined(), z.object({
  'kind': z.literal("internal-skill-candidate-lineage-v3").readonly(),
  'candidateId': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'opportunityId': z.string().readonly(),
  'evaluationEvidenceId': z.string().readonly(),
  'policyId': z.string().readonly(),
  'versionKind': z.literal("experience-authored-bundle-v1").readonly(),
  'contentHash': z.string().readonly(),
  'candidateTreeHash': z.string().readonly(),
  'admissionId': z.string().readonly(),
  'evaluationEnvelopeId': z.string().readonly(),
  'releaseAuthority': z.literal("none").readonly(),
})]).readonly().optional(),
  'promotion': z.object({
  'status': z.union([z.literal("waiting"), z.literal("eligible"), z.literal("blocked")]).readonly(),
  'reason': z.union([z.literal("promotion-governance-unavailable"), z.literal("generation-not-found"), z.literal("generation-workspace-mismatch"), z.literal("review-evidence-invalid"), z.literal("approved-review-missing"), z.literal("approved-review-ambiguous"), z.literal("generation-lineage-mismatch"), z.literal("retention-evidence-invalid"), z.literal("retention-not-run"), z.literal("retention-ambiguous"), z.literal("retention-prepared"), z.literal("retention-regressed"), z.literal("retention-incomplete"), z.literal("retention-verdict-invalid"), z.literal("exact-retention-retained")]).readonly(),
  'retentionId': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
})).readonly(),
}).readonly(),
})
const dsh_evolve_evoforgeEvolution_pause_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_pause_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'workspaceId': z.string().readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_promote_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_promote_parameter_1$schema = z.string()
const dsh_evolve_evoforgeEvolution_promote_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'workspaceId': z.string().readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_rejectReview_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_rejectReview_parameter_1$schema = z.string()
const dsh_evolve_evoforgeEvolution_rejectReview_parameter_2$schema = z.string()
const dsh_evolve_evoforgeEvolution_rejectReview_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'workspaceId': z.string().readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_resume_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_resume_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'workspaceId': z.string().readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_review_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_review_parameter_1$schema = z.string()
const dsh_evolve_evoforgeEvolution_review_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'review': z.object({
  'id': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'status': z.union([z.literal("rejected"), z.literal("pending"), z.literal("approved")]).readonly(),
  'recommendation': z.union([z.literal("review"), z.literal("promote")]).readonly(),
  'skillName': z.string().readonly(),
  'claim': z.string().readonly(),
  'changedFiles': z.array(z.string()).readonly(),
  'candidateTreeHash': z.string().readonly(),
  'lineage': z.union([z.undefined(), z.object({
  'kind': z.literal("internal-skill-candidate-lineage-v3").readonly(),
  'candidateId': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'opportunityId': z.string().readonly(),
  'evaluationEvidenceId': z.string().readonly(),
  'policyId': z.string().readonly(),
  'versionKind': z.literal("experience-authored-bundle-v1").readonly(),
  'contentHash': z.string().readonly(),
  'candidateTreeHash': z.string().readonly(),
  'admissionId': z.string().readonly(),
  'evaluationEnvelopeId': z.string().readonly(),
  'releaseAuthority': z.literal("none").readonly(),
})]).readonly().optional(),
  'cases': z.array(z.object({
  'id': z.string().readonly(),
  'baseline': z.union([z.literal("incomplete"), z.literal("pass"), z.literal("fail")]).readonly(),
  'candidate': z.union([z.literal("incomplete"), z.literal("pass"), z.literal("fail")]).readonly(),
  'passedChecks': z.number().readonly(),
  'totalChecks': z.number().readonly(),
})).readonly(),
  'cost': z.object({
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'trialCount': z.number().readonly(),
}).readonly(),
  'reasons': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'evaluatorVersion': z.string().readonly(),
  'compositionFingerprint': z.string().readonly(),
  'compositionStable': z.boolean().readonly(),
  'startedAt': z.string().readonly(),
  'decisionActor': z.union([z.undefined(), z.literal("human"), z.literal("auto-clear-instruction-v1")]).readonly().optional(),
  'decisionNote': z.union([z.undefined(), z.string()]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activatedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'diff': z.object({
  'patch': z.string().readonly(),
  'shownBytes': z.number().readonly(),
  'totalBytes': z.number().readonly(),
  'truncated': z.boolean().readonly(),
  'impact': z.object({
  'version': z.literal("lexical-protected-effects-v1").readonly(),
  'scope': z.union([z.literal("append-only-skill"), z.literal("broader-change"), z.literal("new-skill")]).readonly(),
  'indicators': z.array(z.union([z.literal("artifact-scope-change"), z.literal("credential-access"), z.literal("destructive-action"), z.literal("messaging-or-calendar"), z.literal("network-access"), z.literal("payment-action"), z.literal("permission-or-sandbox"), z.literal("privileged-tooling"), z.literal("production-change"), z.literal("rewritten-instructions")])).readonly(),
}).readonly(),
}).readonly(),
})
const dsh_evolve_evoforgeEvolution_rollback_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_rollback_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'workspaceId': z.string().readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})

export const TYPERT = {
  package: 'dsh-evolve',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-evolve#evoforgeEvolution/approveReview',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'approveReview',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceId',
          wire: 'workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/approveReview:workspaceId',
            schema: dsh_evolve_evoforgeEvolution_approveReview_parameter_0$schema,
          },
        },
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/approveReview:id',
            schema: dsh_evolve_evoforgeEvolution_approveReview_parameter_1$schema,
          },
        },
        {
          name: 'note',
          wire: 'note',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/approveReview:note',
            schema: dsh_evolve_evoforgeEvolution_approveReview_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_approveReview_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":46,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/overview',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'overview',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceId',
          wire: 'workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/overview:workspaceId',
            schema: dsh_evolve_evoforgeEvolution_overview_parameter_0$schema,
          },
        },
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/overview:sessionId',
            schema: dsh_evolve_evoforgeEvolution_overview_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionOverview',
        schema: dsh_evolve_evoforgeEvolution_overview_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":20,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/pause',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'pause',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceId',
          wire: 'workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/pause:workspaceId',
            schema: dsh_evolve_evoforgeEvolution_pause_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_pause_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":34,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/promote',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'promote',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceId',
          wire: 'workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/promote:workspaceId',
            schema: dsh_evolve_evoforgeEvolution_promote_parameter_0$schema,
          },
        },
        {
          name: 'generationId',
          wire: 'generationId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/promote:generationId',
            schema: dsh_evolve_evoforgeEvolution_promote_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_promote_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":62,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/rejectReview',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'rejectReview',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceId',
          wire: 'workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/rejectReview:workspaceId',
            schema: dsh_evolve_evoforgeEvolution_rejectReview_parameter_0$schema,
          },
        },
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/rejectReview:id',
            schema: dsh_evolve_evoforgeEvolution_rejectReview_parameter_1$schema,
          },
        },
        {
          name: 'note',
          wire: 'note',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/rejectReview:note',
            schema: dsh_evolve_evoforgeEvolution_rejectReview_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_rejectReview_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":54,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/resume',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'resume',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceId',
          wire: 'workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/resume:workspaceId',
            schema: dsh_evolve_evoforgeEvolution_resume_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_resume_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":40,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/review',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'review',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceId',
          wire: 'workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/review:workspaceId',
            schema: dsh_evolve_evoforgeEvolution_review_parameter_0$schema,
          },
        },
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/review:id',
            schema: dsh_evolve_evoforgeEvolution_review_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionReviewDetail',
        schema: dsh_evolve_evoforgeEvolution_review_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":27,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/rollback',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'rollback',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceId',
          wire: 'workspaceId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/rollback:workspaceId',
            schema: dsh_evolve_evoforgeEvolution_rollback_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_rollback_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":69,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "evoforge.evolution",
        "exportName": "EvolutionStore",
        "members": [
          {
            "kind": "method",
            "name": "publishGeneration",
            "signature": "publishGeneration(input: GenerationInput): Promise<{ created: boolean generation: CapabilityGeneration }>"
          },
          {
            "kind": "method",
            "name": "getGeneration",
            "signature": "getGeneration(id: string): CapabilityGeneration | undefined"
          },
          {
            "kind": "method",
            "name": "getActiveGeneration",
            "signature": "getActiveGeneration(workspaceId: string): CapabilityGeneration | undefined"
          },
          {
            "kind": "method",
            "name": "promoteGeneration",
            "signature": "promoteGeneration(workspaceId: string, id: string): Promise<{ previousId: string | undefined generation: CapabilityGeneration }>"
          },
          {
            "kind": "method",
            "name": "rollbackGeneration",
            "signature": "rollbackGeneration(workspaceId: string): Promise<{ previousId: string generation: CapabilityGeneration | undefined }>"
          },
          {
            "kind": "method",
            "name": "pinSession",
            "signature": "pinSession( identity: SessionIdentity, options?: { parentSessionId?: string }, ): Promise<CapabilityGeneration | undefined>"
          },
          {
            "kind": "method",
            "name": "fallbackSessionToNative",
            "signature": "fallbackSessionToNative(identity: SessionIdentity): Promise<void>"
          },
          {
            "kind": "method",
            "name": "getSessionGeneration",
            "signature": "getSessionGeneration(identity: SessionIdentity): CapabilityGeneration | undefined"
          },
          {
            "kind": "method",
            "name": "isRecoveryPaused",
            "signature": "isRecoveryPaused(workspaceId: string): boolean"
          },
          {
            "kind": "method",
            "name": "setRecoveryPaused",
            "signature": "setRecoveryPaused(workspaceId: string, paused: boolean): Promise<{ changed: boolean; paused: boolean }>"
          },
          {
            "kind": "method",
            "name": "close",
            "signature": "close(): Promise<void>"
          }
        ],
        "types": [
          {
            "name": "CapabilityGeneration",
            "declaration": "export interface CapabilityGeneration extends GenerationInput {\n    id: string;\n    schemaVersion: 2;\n}"
          },
          {
            "name": "GenerationInput",
            "declaration": "export interface GenerationInput {\n    workspaceId: string;\n    parentId?: string | undefined;\n    createdAt: number;\n    artifacts: SkillGenerationArtifact[];\n    evaluatorVersion: string;\n    policyVersion: string;\n    compositionFingerprint: string;\n}"
          },
          {
            "name": "GitSkillGenerationArtifact",
            "declaration": "export interface GitSkillGenerationArtifact {\n    kind: 'skill';\n    name: string;\n    gitCommit: string;\n    treeHash: string;\n    lineage?: SkillCandidateLineage | undefined;\n}"
          },
          {
            "name": "SessionIdentity",
            "declaration": "export interface SessionIdentity {\n    workspaceId: string;\n    sessionId: string;\n    createdAt: number;\n    cwd?: string | undefined;\n}"
          },
          {
            "name": "SkillBundleGenerationArtifact",
            "declaration": "export interface SkillBundleGenerationArtifact {\n    kind: 'skill-bundle';\n    name: string;\n    artifactDigest: string;\n    treeHash: string;\n    contentBase64: string;\n    lineage: SkillCandidateLineage;\n}"
          },
          {
            "name": "SkillCandidateLineage",
            "declaration": "export interface SkillCandidateLineage {\n    readonly kind: 'internal-skill-candidate-lineage-v3';\n    readonly candidateId: string;\n    readonly workspaceId: string;\n    readonly skillName: string;\n    readonly opportunityId: string;\n    readonly evaluationEvidenceId: string;\n    readonly policyId: string;\n    readonly versionKind: SkillCandidateVersionKind;\n    readonly contentHash: string;\n    readonly candidateTreeHash: string;\n    readonly admissionId: string;\n    readonly evaluationEnvelopeId: string;\n    readonly releaseAuthority: 'none';\n}"
          },
          {
            "name": "SkillCandidateVersionKind",
            "declaration": "export type SkillCandidateVersionKind = 'experience-authored-bundle-v1';"
          },
          {
            "name": "SkillGenerationArtifact",
            "declaration": "export type SkillGenerationArtifact = GitSkillGenerationArtifact | SkillBundleGenerationArtifact;"
          }
        ]
      },
      {
        "description": "Generated-Remote transport adapter; all policy and state remain in EvolutionControlPlane.",
        "summary": "Generated-Remote transport adapter; all policy and state remain in EvolutionControlPlane.",
        "tags": [],
        "jsDoc": "/** Generated-Remote transport adapter; all policy and state remain in EvolutionControlPlane. */",
        "key": "evoforge.evolutionControl",
        "exportName": "EvolutionRemoteService",
        "members": [
          {
            "kind": "method",
            "name": "overview",
            "signature": "overview(workspaceId: string, sessionId?: string): Promise<EvolutionOverview>"
          },
          {
            "kind": "method",
            "name": "review",
            "signature": "review(workspaceId: string, id: string): Promise<EvolutionReviewDetail>"
          },
          {
            "kind": "method",
            "name": "pause",
            "signature": "pause(workspaceId: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "resume",
            "signature": "resume(workspaceId: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "approveReview",
            "signature": "approveReview(workspaceId: string, id: string, note: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "rejectReview",
            "signature": "rejectReview(workspaceId: string, id: string, note: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "promote",
            "signature": "promote(workspaceId: string, generationId: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "rollback",
            "signature": "rollback(workspaceId: string): Promise<EvolutionActionReceipt>"
          }
        ],
        "types": [
          {
            "name": "CandidateImpactIndicator",
            "declaration": "export type CandidateImpactIndicator = 'artifact-scope-change' | 'credential-access' | 'destructive-action' | 'messaging-or-calendar' | 'network-access' | 'payment-action' | 'permission-or-sandbox' | 'privileged-tooling' | 'production-change' | 'rewritten-instructions';"
          },
          {
            "name": "CandidateImpactProjection",
            "declaration": "export interface CandidateImpactProjection {\n    readonly version: 'lexical-protected-effects-v1';\n    readonly scope: 'append-only-skill' | 'broader-change' | 'new-skill';\n    readonly indicators: readonly CandidateImpactIndicator[];\n}"
          },
          {
            "name": "DeliveryOutcomeCounts",
            "declaration": "export interface DeliveryOutcomeCounts {\n    readonly total: number;\n    readonly passed: number;\n    readonly failed: number;\n    readonly unknown: number;\n}"
          },
          {
            "name": "EvolutionActionReceipt",
            "declaration": "export interface EvolutionActionReceipt {\n    readonly schemaVersion: 1;\n    readonly workspaceId: string;\n    readonly action: 'pause' | 'resume' | 'approve-review' | 'reject-review' | 'promote' | 'rollback';\n    readonly reviewId?: string;\n    readonly status?: 'approved' | 'rejected';\n    readonly generationId?: string;\n    readonly previousGenerationId?: string;\n    readonly activeGenerationId?: string;\n    readonly recoveryPaused?: boolean;\n}"
          },
          {
            "name": "EvolutionArtifactView",
            "declaration": "export interface EvolutionArtifactView {\n    readonly kind: 'skill' | 'skill-bundle';\n    readonly name: string;\n    readonly gitCommit?: string;\n    readonly artifactDigest?: string;\n    readonly treeHash: string;\n    readonly lineage?: EvolutionSkillCandidateLineageView;\n}"
          },
          {
            "name": "EvolutionCapabilityGapQueueView",
            "declaration": "export interface EvolutionCapabilityGapQueueView {\n    readonly confirmedCount: number;\n    readonly items: readonly EvolutionCapabilityGapView[];\n}"
          },
          {
            "name": "EvolutionCapabilityGapView",
            "declaration": "export interface EvolutionCapabilityGapView {\n    readonly id: string;\n    readonly observedAt: number;\n    readonly requestedSkill: string;\n    readonly catalogHash: string;\n    readonly catalogSize: number;\n    readonly generationId?: string;\n    readonly goal?: { readonly id: string; readonly revision: number; readonly objective?: string; };\n    readonly status: 'confirmed';\n    readonly evidence: { readonly kind: 'native-skill-miss'; readonly catalog: 'complete'; readonly routing: 'requested-skill-absent'; readonly providers: 'settled'; } | { readonly kind: 'model-declared-skill-gap'; readonly catalog: 'complete'; readonly routing: 'model-declared-no-applicable-skill'; readonly providers: 'settled'; };\n}"
          },
          {
            "name": "EvolutionCapabilityMapView",
            "declaration": "export interface EvolutionCapabilityMapView {\n    readonly status: 'unobserved' | 'complete' | 'incomplete';\n    readonly catalogHash?: string;\n    readonly capabilities: readonly EvolutionCapabilityView[];\n}"
          },
          {
            "name": "EvolutionCapabilityRoute",
            "declaration": "export type EvolutionCapabilityRoute = 'available' | 'model-selected' | 'user-selected';"
          },
          {
            "name": "EvolutionCapabilityView",
            "declaration": "export interface EvolutionCapabilityView {\n    readonly name: string;\n    readonly description: string;\n    readonly source: string;\n    readonly provider: string;\n    readonly scope: 'workspace-session';\n    readonly invocation: { readonly model: boolean; readonly user: boolean; };\n    readonly versionKind: 'provider-managed' | 'evolved-tree';\n    readonly version?: string;\n    readonly generationId?: string;\n    readonly route: EvolutionCapabilityRoute;\n}"
          },
          {
            "name": "EvolutionDeliveryMetricEvidenceView",
            "declaration": "export interface EvolutionDeliveryMetricEvidenceView {\n    readonly outcomeId: string;\n    readonly observedAt: number;\n    readonly generationId?: string;\n    readonly status: 'passed' | 'failed' | 'unknown';\n    readonly goal: { readonly id: string; readonly revision: number; };\n    readonly metrics: { readonly schemaVersion: 1; readonly source: 'dsh-session-projections'; readonly goalId: string; readonly throughEventSeq: number; readonly attributedTurns: number; readonly closedSteps: number; readonly activeWallMs: number; readonly providerUsage: EvolutionProviderUsageView; readonly latency: EvolutionLatencyView; readonly monetaryCost: { readonly status: 'unavailable'; readonly reason: 'provider-price-not-projected'; }; };\n}"
          },
          {
            "name": "EvolutionDeliveryMetricRollupView",
            "declaration": "export interface EvolutionDeliveryMetricRollupView {\n    readonly measured: number;\n    readonly unmeasured: number;\n    readonly attributedTurns: number;\n    readonly closedSteps: number;\n    readonly activeWallMs: number;\n    readonly providerUsage: EvolutionProviderUsageView;\n    readonly latency: EvolutionLatencyView;\n    readonly monetaryCost: { readonly status: 'unavailable'; readonly reason: 'provider-price-not-projected'; };\n}"
          },
          {
            "name": "EvolutionFutureSessionPromotionReason",
            "declaration": "export type EvolutionFutureSessionPromotionReason = 'promotion-governance-unavailable' | 'generation-not-found' | 'generation-workspace-mismatch' | 'review-evidence-invalid' | 'approved-review-missing' | 'approved-review-ambiguous' | 'generation-lineage-mismatch' | 'retention-evidence-invalid' | 'retention-not-run' | 'retention-ambiguous' | 'retention-prepared' | 'retention-regressed' | 'retention-incomplete' | 'retention-verdict-invalid' | 'exact-retention-retained';"
          },
          {
            "name": "EvolutionGenerationView",
            "declaration": "export interface EvolutionGenerationView {\n    readonly id: string;\n    readonly workspaceId: string;\n    readonly rollbackTargetId?: string;\n    readonly createdAt: number;\n    readonly evaluatorVersion: string;\n    readonly policyVersion: string;\n    readonly artifacts: readonly EvolutionArtifactView[];\n}"
          },
          {
            "name": "EvolutionInactiveGenerationView",
            "declaration": "export interface EvolutionInactiveGenerationView {\n    readonly workspaceId: string;\n    readonly generationId: string;\n    readonly reviewId: string;\n    readonly skillName: string;\n    readonly lineage?: EvolutionSkillCandidateLineageView;\n    readonly promotion: { readonly status: 'eligible' | 'waiting' | 'blocked'; readonly reason: EvolutionFutureSessionPromotionReason; readonly retentionId?: string; };\n}"
          },
          {
            "name": "EvolutionLatencyView",
            "declaration": "export interface EvolutionLatencyView {\n    readonly llmMs: number;\n    readonly toolMs: number;\n    readonly ttftMs: number;\n    readonly ttftSteps: number;\n    readonly decodeMs: number;\n    readonly decodeTokens: number;\n}"
          },
          {
            "name": "EvolutionOverview",
            "declaration": "export interface EvolutionOverview {\n    readonly schemaVersion: 1;\n    readonly workspaceId: string;\n    readonly active?: EvolutionGenerationView;\n    readonly recovery: { readonly available: boolean; readonly paused?: boolean; };\n    readonly capabilityMap?: EvolutionCapabilityMapView;\n    readonly capabilityGaps?: EvolutionCapabilityGapQueueView;\n    readonly skillOpportunities?: EvolutionSkillOpportunityQueueView;\n    readonly skillImprovementOpportunities?: EvolutionSkillImprovementOpportunityQueueView;\n    readonly skillCandidates?: EvolutionSkillCandidateQueueView;\n    readonly slowLoopAuthoring?: EvolutionSlowLoopAuthoringView;\n    readonly skillEvaluationGovernance?: EvolutionSkillEvaluationGovernanceView;\n    readonly skillAdmission?: EvolutionSkillAdmissionView;\n    readonly skillEvaluationRuns?: EvolutionSkillEvaluationRunsView;\n    readonly deliveryOutcomes?: { readonly all: DeliveryOutcomeCounts; readonly selected: DeliveryOutcomeCounts; readonly baseline?: DeliveryOutcomeCounts; readonly metrics: { readonly all: EvolutionDeliveryMetricRollupView; readonly selected: EvolutionDeliveryMetricRollupView; readonly baseline?: EvolutionDeliveryMetricRollupView; readonly recent: readonly EvolutionDeliveryMetricEvidenceView[]; }; };\n    readonly feedbackSignals?: { readonly all: number; readonly selected: number; };\n    readonly reviews: { readonly available: boolean; readonly pendingCount: number; readonly actionableCount: number; readonly warningCount: number; readonly items: readonly EvolutionReviewView[]; readonly inactiveGenerations: readonly EvolutionInactiveGenerationView[]; };\n}"
          },
          {
            "name": "EvolutionProviderUsageView",
            "declaration": "export interface EvolutionProviderUsageView {\n    readonly uncachedInputTokens: number;\n    readonly outputTokens: number;\n    readonly cacheReadTokens: number;\n    readonly cacheWriteTokens: number;\n}"
          },
          {
            "name": "EvolutionReviewCaseView",
            "declaration": "export interface EvolutionReviewCaseView {\n    readonly id: string;\n    readonly baseline: 'pass' | 'fail' | 'incomplete';\n    readonly candidate: 'pass' | 'fail' | 'incomplete';\n    readonly passedChecks: number;\n    readonly totalChecks: number;\n}"
          },
          {
            "name": "EvolutionReviewDetail",
            "declaration": "export interface EvolutionReviewDetail {\n    readonly schemaVersion: 1;\n    readonly review: EvolutionReviewView;\n    readonly diff: { readonly patch: string; readonly shownBytes: number; readonly totalBytes: number; readonly truncated: boolean; readonly impact: CandidateImpactProjection; };\n}"
          },
          {
            "name": "EvolutionReviewView",
            "declaration": "export interface EvolutionReviewView {\n    readonly id: string;\n    readonly workspaceId: string;\n    readonly status: 'pending' | 'approved' | 'rejected';\n    readonly recommendation: 'promote' | 'review';\n    readonly skillName: string;\n    readonly claim: string;\n    readonly changedFiles: readonly string[];\n    readonly candidateTreeHash: string;\n    readonly lineage?: EvolutionSkillCandidateLineageView;\n    readonly cases: readonly EvolutionReviewCaseView[];\n    readonly cost: { readonly inputTokens: number; readonly outputTokens: number; readonly trialCount: number; };\n    readonly reasons: readonly string[];\n    readonly limitations: readonly string[];\n    readonly evaluatorVersion: string;\n    readonly compositionFingerprint: string;\n    readonly compositionStable: boolean;\n    readonly startedAt: string;\n    readonly decisionActor?: 'human' | 'auto-clear-instruction-v1';\n    readonly decisionNote?: string;\n    readonly generationId?: string;\n    readonly activatedAt?: string;\n}"
          },
          {
            "name": "EvolutionSkillAdmissionView",
            "declaration": "export interface EvolutionSkillAdmissionView {\n    readonly configuredPolicyCount: number;\n    readonly warningCount: number;\n    readonly results: readonly { readonly id: string; readonly candidateId: string; readonly skillName: string; readonly status: 'abstained' | 'protected' | 'incomplete' | 'rejected' | 'review' | 'qualified-for-shadow'; readonly reasons: readonly ('no-current-evaluation-envelope' | 'candidate-has-executable-content' | 'candidate-is-not-instruction-only' | 'baseline-identity-mismatch' | 'case-pack-identity-mismatch' | 'assembled-evaluator-not-governance-separated' | 'case-pack-calibration-failed' | 'candidate-failed-admission' | 'baseline-already-passes' | 'candidate-improves-deterministic-admission' | 'governance-input-mutated' | 'governance-roots-overlap' | 'evaluation-failed')[]; readonly envelopeId?: string; readonly releaseAuthority: 'none'; readonly evidence?: { readonly baseline: 'pass' | 'fail'; readonly candidate: 'pass' | 'fail'; readonly calibrationPassed: boolean; readonly candidateExecuted: false; readonly evaluatorClass: 'deterministic-filesystem'; readonly trialCount: 4; }; }[];\n}"
          },
          {
            "name": "EvolutionSkillCandidateLineageView",
            "declaration": "export interface EvolutionSkillCandidateLineageView {\n    readonly kind: 'internal-skill-candidate-lineage-v3';\n    readonly candidateId: string;\n    readonly workspaceId: string;\n    readonly skillName: string;\n    readonly opportunityId: string;\n    readonly evaluationEvidenceId: string;\n    readonly policyId: string;\n    readonly versionKind: EvolutionSkillCandidateVersionKind;\n    readonly contentHash: string;\n    readonly candidateTreeHash: string;\n    readonly admissionId: string;\n    readonly evaluationEnvelopeId: string;\n    readonly releaseAuthority: 'none';\n}"
          },
          {
            "name": "EvolutionSkillCandidateQueueView",
            "declaration": "export interface EvolutionSkillCandidateQueueView {\n    readonly quarantinedCount: number;\n    readonly items: readonly EvolutionSkillCandidateView[];\n}"
          },
          {
            "name": "EvolutionSkillCandidateVersionKind",
            "declaration": "export type EvolutionSkillCandidateVersionKind = 'experience-authored-bundle-v1';"
          },
          {
            "name": "EvolutionSkillCandidateView",
            "declaration": "export interface EvolutionSkillCandidateView {\n    readonly id: string;\n    readonly createdAt: number;\n    readonly skillName: string;\n    readonly description: string;\n    readonly opportunity: { readonly kind: 'internal-experience-v1'; readonly id: string; readonly gapIds: readonly string[]; readonly goalCount: number; };\n    readonly authorship: { readonly kind: 'bounded-model-authoring-v1'; readonly policyId: string; readonly modelIdentityHash: string; readonly evaluationEvidenceId: string; readonly inputDigest: string; };\n    readonly scope: 'workspace';\n    readonly version: { readonly kind: 'experience-authored-bundle-v1'; readonly artifactDigest: string; readonly treeHash: string; };\n    readonly contentHash: string;\n    readonly package: { readonly path: string; readonly fileCount: number; readonly totalBytes: number; readonly hasScripts: boolean; readonly hasReferences: boolean; };\n    readonly permissions: { readonly declared: boolean; readonly executableContent: boolean; readonly externalEffects: 'unknown'; };\n    readonly license?: { readonly status: 'declared'; readonly value: string; } | { readonly status: 'unknown'; };\n    readonly safety: { readonly status: 'quarantined'; readonly checks: readonly { readonly name: 'artifact-digest-integrity' | 'regular-files-only' | 'skill-identity' | 'effect-review'; readonly status: 'passed' | 'required'; }[]; };\n    readonly lifecycle: 'inactive';\n    readonly verification: 'unevaluated';\n    readonly execution: 'never';\n}"
          },
          {
            "name": "EvolutionSkillEvaluationGovernanceView",
            "declaration": "export interface EvolutionSkillEvaluationGovernanceView {\n    readonly configuredPolicyCount: number;\n    readonly warningCount: number;\n    readonly runs: readonly { readonly id: string; readonly policyId: string; readonly skillName: string; readonly opportunityId: string; readonly evaluationEvidenceId: string; readonly phase: 'prepared' | 'budget-deferred' | 'authoring-pending' | 'admission-ready' | 'holdout-ready' | 'authored' | 'uncertain' | 'incomplete' | 'ready'; readonly pendingRole?: 'admission' | 'holdout' | 'retention'; readonly createdAt: string; readonly updatedAt: string; readonly modelCalls: number; readonly inputTokens: number; readonly outputTokens: number; readonly retentionIncluded: boolean; readonly retryAt?: number; readonly failure?: 'paid-authoring-uncertain' | 'admission-calibration-failed' | 'holdout-calibration-failed' | 'retention-calibration-failed' | 'governance-incomplete'; readonly releaseAuthority: 'none'; }[];\n}"
          },
          {
            "name": "EvolutionSkillEvaluationRunsView",
            "declaration": "export interface EvolutionSkillEvaluationRunsView {\n    readonly configuredRetentionRootCount: number;\n    readonly warningCount: number;\n    readonly items: readonly { readonly candidateId: string; readonly skillName: string; readonly lineage: EvolutionSkillCandidateLineageView; readonly shadow: { readonly runId: string; readonly status: 'complete'; readonly recommendation: 'promote' | 'review'; readonly cases: readonly EvolutionReviewCaseView[]; readonly cost: { readonly inputTokens: number; readonly outputTokens: number; readonly trialCount: number; }; readonly compositionStable: boolean; readonly startedAt: string; }; readonly retention?: { readonly id: string; readonly status: 'prepared' | 'retained' | 'regressed' | 'incomplete'; readonly reason?: EvolutionSkillRetentionReason; readonly startedAt?: string; readonly finishedAt?: string; readonly evidence?: { readonly baseline: 'pass' | 'fail'; readonly candidate: 'pass' | 'fail'; readonly calibrationPassed: boolean; readonly compositionStable: boolean; readonly proposerCalls: 0; readonly trialCount: 4; readonly modelCalls?: { readonly baseline: number; readonly candidate: number; }; readonly usage?: { readonly baseline: { readonly inputTokens: number; readonly outputTokens: number; readonly cacheReadTokens: number; readonly cacheWriteTokens: number; readonly reasoningTokens: number; }; readonly candidate: { readonly inputTokens: number; readonly outputTokens: number; readonly cacheReadTokens: number; readonly cacheWriteTokens: number; readonly reasoningTokens: number; }; }; }; readonly releaseAuthority: 'none'; }; readonly releaseAuthority: 'none'; }[];\n}"
          },
          {
            "name": "EvolutionSkillImprovementOpportunityQueueView",
            "declaration": "export interface EvolutionSkillImprovementOpportunityQueueView {\n    readonly waitingCount: number;\n    readonly items: readonly EvolutionSkillImprovementOpportunityView[];\n}"
          },
          {
            "name": "EvolutionSkillImprovementOpportunityView",
            "declaration": "export interface EvolutionSkillImprovementOpportunityView {\n    readonly id: string;\n    readonly skillName: string;\n    readonly invocationContentHash: string;\n    readonly feedbackSignalIds: readonly string[];\n    readonly goalIds: readonly string[];\n    readonly signalCount: number;\n    readonly goalCount: number;\n    readonly firstObservedAt: number;\n    readonly lastObservedAt: number;\n    readonly evidence: { readonly kind: 'internal-exact-skill-corrections-v1'; readonly association: 'exact-durable-skill-invocation-content'; readonly eligibilityBasis: 'two-or-more-distinct-goals-same-invocation-content'; readonly referencesTruncated: boolean; readonly causalClaim: 'none'; };\n    readonly status: 'waiting-for-baseline-bundle';\n    readonly releaseAuthority: 'none';\n}"
          },
          {
            "name": "EvolutionSkillOpportunityQueueView",
            "declaration": "export interface EvolutionSkillOpportunityQueueView {\n    readonly eligibleCount: number;\n    readonly items: readonly EvolutionSkillOpportunityView[];\n}"
          },
          {
            "name": "EvolutionSkillOpportunityView",
            "declaration": "export interface EvolutionSkillOpportunityView {\n    readonly id: string;\n    readonly skillName: string;\n    readonly gapIds: readonly string[];\n    readonly goalIds: readonly string[];\n    readonly gapCount: number;\n    readonly goalCount: number;\n    readonly firstObservedAt: number;\n    readonly lastObservedAt: number;\n    readonly evidence: { readonly kind: 'internal-experience-v3'; readonly eligibilityBasis: 'two-or-more-distinct-goals'; readonly correctionSignals: { readonly association: 'exact-durable-skill-invocation'; readonly count: number; readonly goalCount: number; readonly ids: readonly string[]; readonly referencesTruncated: boolean; }; readonly deliveryOutcomes: { readonly association: 'same-goal-single-skill-gap'; readonly total: number; readonly passed: number; readonly failed: number; readonly unknown: number; readonly ids: readonly string[]; readonly referencesTruncated: boolean; }; readonly causalClaim: 'none'; };\n    readonly evaluationReadiness: { readonly status: 'ready-to-seal' | 'sealed'; readonly evidenceId: string; readonly observedGoalCount: number; readonly authoringGoalCount: number; readonly admissionGoalCount: number; readonly holdoutGoalCount: number; readonly retentionGoalCount: number; readonly proposerCanReadProtectedSamples: false; readonly releaseAuthority: 'none'; } | { readonly status: 'waiting'; readonly reason: 'fewer-than-four-independent-goals'; readonly observedGoalCount: number; readonly requiredGoalCount: 4; readonly releaseAuthority: 'none'; } | { readonly status: 'unavailable'; readonly reason: 'governance-policy-unavailable'; readonly observedGoalCount: number; readonly releaseAuthority: 'none'; } | { readonly status: 'invalid'; readonly reason: 'opportunity-evidence-invalid'; readonly observedGoalCount: number; readonly releaseAuthority: 'none'; };\n    readonly status: 'eligible-for-authoring';\n    readonly releaseAuthority: 'none';\n}"
          },
          {
            "name": "EvolutionSkillRetentionReason",
            "declaration": "export type EvolutionSkillRetentionReason = 'no-independent-retention-case' | 'shadow-not-complete' | 'shadow-not-promotable' | 'retention-trial-failed' | 'retention-input-mutated' | 'retention-not-assembled' | 'retention-calibration-failed' | 'prior-case-baseline-failed' | 'non-target-composition-changed' | 'candidate-regressed-prior-case' | 'candidate-retained-prior-case';"
          },
          {
            "name": "EvolutionSlowLoopAuthoringView",
            "declaration": "export interface EvolutionSlowLoopAuthoringView {\n    readonly configuredPolicyCount: number;\n    readonly warningCount: number;\n    readonly runs: readonly { readonly id: string; readonly targetId: string; readonly skillName: string; readonly opportunityId: string; readonly gapCount: number; readonly goalCount: number; readonly phase: 'prepared' | 'budget-deferred' | 'cancelled' | 'authoring-pending' | 'uncertain' | 'incomplete' | 'candidate-ready'; readonly createdAt: string; readonly updatedAt: string; readonly modelCalls: 0 | 1; readonly inputTokens: number; readonly outputTokens: number; readonly candidateId?: string; readonly retryAt?: number; readonly releaseAuthority: 'none'; }[];\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "Host-only wakeup after the resident evaluation scan has settled.",
        "summary": "Host-only wakeup after the resident evaluation scan has settled.",
        "tags": [],
        "jsDoc": "/** Host-only wakeup after the resident evaluation scan has settled. */",
        "name": "evoforge/evolution/settled",
        "signature": "'evoforge/evolution/settled'(): void"
      }
    ],
    "objects": []
  },
}
