/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_evolve_evoforgeEvolution_approveEvaluator_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_approveEvaluator_parameter_1$schema = z.string()
const dsh_evolve_evoforgeEvolution_approveEvaluator_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_approveReview_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_approveReview_parameter_1$schema = z.string()
const dsh_evolve_evoforgeEvolution_approveReview_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_authorEvaluator_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_authorEvaluator_parameter_1$schema = z.string()
const dsh_evolve_evoforgeEvolution_authorEvaluator_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_evaluatorDraft_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_evaluatorDraft_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'draft': z.object({
  'id': z.string().readonly(),
  'launchId': z.string().readonly(),
  'targetId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'status': z.union([z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected")]).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'cost': z.object({
  'modelCalls': z.union([z.literal(0), z.literal(1)]).readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
}).readonly(),
}).readonly(),
  'files': z.array(z.object({
  'path': z.string().readonly(),
  'content': z.string().readonly(),
})).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'qualifiedShadowAvailable': z.boolean().readonly(),
  'decision': z.union([z.undefined(), z.object({
  'actor': z.literal("human").readonly(),
  'note': z.string().readonly(),
  'decidedAt': z.string().readonly(),
})]).readonly().optional(),
  'qualification': z.union([z.undefined(), z.object({
  'calibrated': z.boolean().readonly(),
  'attempt': z.number().readonly(),
})]).readonly().optional(),
  'reason': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_overview_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'active': z.union([z.undefined(), z.object({
  'id': z.string().readonly(),
  'rollbackTargetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'createdAt': z.number().readonly(),
  'evaluatorVersion': z.string().readonly(),
  'policyVersion': z.string().readonly(),
  'artifacts': z.array(z.object({
  'kind': z.literal("skill").readonly(),
  'name': z.string().readonly(),
  'gitCommit': z.string().readonly(),
  'treeHash': z.string().readonly(),
})).readonly(),
})]).readonly().optional(),
  'recovery': z.object({
  'available': z.boolean().readonly(),
  'paused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
}).readonly(),
  'automaticPromotion': z.object({
  'enabled': z.boolean().readonly(),
  'skills': z.array(z.string()).readonly(),
}).readonly(),
  'deliveryOutcomes': z.union([z.undefined(), z.object({
  'all': z.object({
  'total': z.number().readonly(),
  'passed': z.number().readonly(),
  'failed': z.number().readonly(),
  'unknown': z.number().readonly(),
}).readonly(),
  'selected': z.object({
  'total': z.number().readonly(),
  'passed': z.number().readonly(),
  'failed': z.number().readonly(),
  'unknown': z.number().readonly(),
}).readonly(),
})]).readonly().optional(),
  'feedbackSignals': z.union([z.undefined(), z.object({
  'all': z.number().readonly(),
  'selected': z.number().readonly(),
})]).readonly().optional(),
  'feedbackShadow': z.union([z.undefined(), z.object({
  'available': z.boolean().readonly(),
  'warningCount': z.number().readonly(),
  'signals': z.array(z.object({
  'id': z.string().readonly(),
  'sourceUpdatedAt': z.number().readonly(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'targets': z.array(z.object({
  'id': z.string().readonly(),
  'skillName': z.string().readonly(),
})).readonly(),
  'runs': z.array(z.object({
  'launchId': z.string().readonly(),
  'targetId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'phase': z.union([z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete")]).readonly(),
  'startedAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly(),
})]).readonly().optional(),
  'automaticFeedbackBudget': z.union([z.undefined(), z.object({
  'warningCount': z.number().readonly(),
  'targets': z.array(z.object({
  'targetId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'utcDay': z.string().readonly(),
  'used': z.number().readonly(),
  'limit': z.number().readonly(),
  'remaining': z.number().readonly(),
  'status': z.union([z.literal("ready"), z.literal("unknown")]).readonly(),
})).readonly(),
})]).readonly().optional(),
  'evaluatorAuthoring': z.union([z.undefined(), z.object({
  'available': z.boolean().readonly(),
  'warningCount': z.number().readonly(),
  'signals': z.array(z.object({
  'id': z.string().readonly(),
  'sourceUpdatedAt': z.number().readonly(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'targets': z.array(z.object({
  'id': z.string().readonly(),
  'skillName': z.string().readonly(),
})).readonly(),
  'drafts': z.array(z.object({
  'id': z.string().readonly(),
  'launchId': z.string().readonly(),
  'targetId': z.string().readonly(),
  'skillName': z.string().readonly(),
  'status': z.union([z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected")]).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'cost': z.object({
  'modelCalls': z.union([z.literal(0), z.literal(1)]).readonly(),
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
}).readonly(),
})).readonly(),
})]).readonly().optional(),
  'reviews': z.object({
  'available': z.boolean().readonly(),
  'pendingCount': z.number().readonly(),
  'actionableCount': z.number().readonly(),
  'warningCount': z.number().readonly(),
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'status': z.union([z.literal("rejected"), z.literal("pending"), z.literal("approved")]).readonly(),
  'recommendation': z.union([z.literal("promote"), z.literal("review")]).readonly(),
  'skillName': z.string().readonly(),
  'claim': z.string().readonly(),
  'changedFiles': z.array(z.string()).readonly(),
  'candidateTreeHash': z.string().readonly(),
  'cases': z.array(z.object({
  'id': z.string().readonly(),
  'baseline': z.union([z.literal("incomplete"), z.literal("pass"), z.literal("fail")]).readonly(),
  'candidate': z.union([z.literal("incomplete"), z.literal("pass"), z.literal("fail")]).readonly(),
  'passedChecks': z.number().readonly(),
  'totalChecks': z.number().readonly(),
})).readonly(),
  'cost': z.object({
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'trialCount': z.number().readonly(),
}).readonly(),
  'reasons': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'evaluatorVersion': z.string().readonly(),
  'compositionFingerprint': z.string().readonly(),
  'compositionStable': z.boolean().readonly(),
  'startedAt': z.string().readonly(),
  'decisionActor': z.union([z.undefined(), z.literal("human"), z.literal("auto-clear-instruction-v1")]).readonly().optional(),
  'decisionNote': z.union([z.undefined(), z.string()]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activatedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
})).readonly(),
  'inactiveGenerations': z.array(z.object({
  'generationId': z.string().readonly(),
  'reviewId': z.string().readonly(),
  'skillName': z.string().readonly(),
})).readonly(),
}).readonly(),
})
const dsh_evolve_evoforgeEvolution_pause_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_promote_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_promote_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_rejectEvaluator_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_rejectEvaluator_parameter_1$schema = z.string()
const dsh_evolve_evoforgeEvolution_rejectEvaluator_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_rejectReview_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_rejectReview_parameter_1$schema = z.string()
const dsh_evolve_evoforgeEvolution_rejectReview_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_resume_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_review_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_review_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'review': z.object({
  'id': z.string().readonly(),
  'status': z.union([z.literal("rejected"), z.literal("pending"), z.literal("approved")]).readonly(),
  'recommendation': z.union([z.literal("promote"), z.literal("review")]).readonly(),
  'skillName': z.string().readonly(),
  'claim': z.string().readonly(),
  'changedFiles': z.array(z.string()).readonly(),
  'candidateTreeHash': z.string().readonly(),
  'cases': z.array(z.object({
  'id': z.string().readonly(),
  'baseline': z.union([z.literal("incomplete"), z.literal("pass"), z.literal("fail")]).readonly(),
  'candidate': z.union([z.literal("incomplete"), z.literal("pass"), z.literal("fail")]).readonly(),
  'passedChecks': z.number().readonly(),
  'totalChecks': z.number().readonly(),
})).readonly(),
  'cost': z.object({
  'inputTokens': z.number().readonly(),
  'outputTokens': z.number().readonly(),
  'trialCount': z.number().readonly(),
}).readonly(),
  'reasons': z.array(z.string()).readonly(),
  'limitations': z.array(z.string()).readonly(),
  'evaluatorVersion': z.string().readonly(),
  'compositionFingerprint': z.string().readonly(),
  'compositionStable': z.boolean().readonly(),
  'startedAt': z.string().readonly(),
  'decisionActor': z.union([z.undefined(), z.literal("human"), z.literal("auto-clear-instruction-v1")]).readonly().optional(),
  'decisionNote': z.union([z.undefined(), z.string()]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activatedAt': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'diff': z.object({
  'patch': z.string().readonly(),
  'shownBytes': z.number().readonly(),
  'totalBytes': z.number().readonly(),
  'truncated': z.boolean().readonly(),
  'impact': z.object({
  'version': z.literal("lexical-protected-effects-v1").readonly(),
  'scope': z.union([z.literal("append-only-skill"), z.literal("broader-change")]).readonly(),
  'indicators': z.array(z.union([z.literal("artifact-scope-change"), z.literal("credential-access"), z.literal("destructive-action"), z.literal("messaging-or-calendar"), z.literal("network-access"), z.literal("payment-action"), z.literal("permission-or-sandbox"), z.literal("privileged-tooling"), z.literal("production-change"), z.literal("rewritten-instructions")])).readonly(),
}).readonly(),
}).readonly(),
  'automatic': z.union([z.undefined(), z.object({
  'eligible': z.boolean().readonly(),
  'policyVersion': z.literal("auto-clear-instruction-v1").readonly(),
  'reasons': z.array(z.string()).readonly(),
})]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_rollback_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_startEvaluatorShadow_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_startEvaluatorShadow_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})
const dsh_evolve_evoforgeEvolution_startFeedbackShadow_parameter_0$schema = z.string()
const dsh_evolve_evoforgeEvolution_startFeedbackShadow_parameter_1$schema = z.string()
const dsh_evolve_evoforgeEvolution_startFeedbackShadow_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'action': z.union([z.literal("promote"), z.literal("pause"), z.literal("resume"), z.literal("approve-review"), z.literal("reject-review"), z.literal("rollback"), z.literal("start-shadow"), z.literal("author-evaluator"), z.literal("approve-evaluator"), z.literal("reject-evaluator")]).readonly(),
  'reviewId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("rejected"), z.literal("approved")]).readonly().optional(),
  'generationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'previousGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'activeGenerationId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'recoveryPaused': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
  'launchId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'targetId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'skillName': z.union([z.undefined(), z.string()]).readonly().optional(),
  'runStatus': z.union([z.undefined(), z.literal("prepared"), z.literal("proposal-pending"), z.literal("candidate-ready"), z.literal("trial-running"), z.literal("complete"), z.literal("incomplete"), z.literal("scheduled")]).readonly().optional(),
  'jobId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'draftStatus': z.union([z.undefined(), z.literal("incomplete"), z.literal("authoring-pending"), z.literal("uncertain"), z.literal("draft-ready"), z.literal("qualification-running"), z.literal("qualified"), z.literal("rejected"), z.literal("scheduled")]).readonly().optional(),
})

export const TYPERT = {
  package: 'dsh-evolve',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-evolve#evoforgeEvolution/approveEvaluator',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'approveEvaluator',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/approveEvaluator:id',
            schema: dsh_evolve_evoforgeEvolution_approveEvaluator_parameter_0$schema,
          },
        },
        {
          name: 'note',
          wire: 'note',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/approveEvaluator:note',
            schema: dsh_evolve_evoforgeEvolution_approveEvaluator_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_approveEvaluator_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":87,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/approveReview',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'approveReview',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/approveReview:id',
            schema: dsh_evolve_evoforgeEvolution_approveReview_parameter_0$schema,
          },
        },
        {
          name: 'note',
          wire: 'note',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/approveReview:note',
            schema: dsh_evolve_evoforgeEvolution_approveReview_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_approveReview_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":42,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/authorEvaluator',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'authorEvaluator',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'signalId',
          wire: 'signalId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/authorEvaluator:signalId',
            schema: dsh_evolve_evoforgeEvolution_authorEvaluator_parameter_0$schema,
          },
        },
        {
          name: 'targetId',
          wire: 'targetId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/authorEvaluator:targetId',
            schema: dsh_evolve_evoforgeEvolution_authorEvaluator_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_authorEvaluator_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":80,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/evaluatorDraft',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'evaluatorDraft',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/evaluatorDraft:id',
            schema: dsh_evolve_evoforgeEvolution_evaluatorDraft_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionEvaluatorDraftDetail',
        schema: dsh_evolve_evoforgeEvolution_evaluatorDraft_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":74,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/overview',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'overview',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionOverview',
        schema: dsh_evolve_evoforgeEvolution_overview_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":21,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/pause',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'pause',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_pause_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":32,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/promote',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'promote',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'generationId',
          wire: 'generationId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/promote:generationId',
            schema: dsh_evolve_evoforgeEvolution_promote_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_promote_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":56,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/rejectEvaluator',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'rejectEvaluator',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/rejectEvaluator:id',
            schema: dsh_evolve_evoforgeEvolution_rejectEvaluator_parameter_0$schema,
          },
        },
        {
          name: 'note',
          wire: 'note',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/rejectEvaluator:note',
            schema: dsh_evolve_evoforgeEvolution_rejectEvaluator_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_rejectEvaluator_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":94,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/rejectReview',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'rejectReview',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/rejectReview:id',
            schema: dsh_evolve_evoforgeEvolution_rejectReview_parameter_0$schema,
          },
        },
        {
          name: 'note',
          wire: 'note',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/rejectReview:note',
            schema: dsh_evolve_evoforgeEvolution_rejectReview_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_rejectReview_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":49,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/resume',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'resume',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_resume_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":37,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/review',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'review',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/review:id',
            schema: dsh_evolve_evoforgeEvolution_review_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionReviewDetail',
        schema: dsh_evolve_evoforgeEvolution_review_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":26,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/rollback',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'rollback',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_rollback_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":62,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/startEvaluatorShadow',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'startEvaluatorShadow',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/startEvaluatorShadow:id',
            schema: dsh_evolve_evoforgeEvolution_startEvaluatorShadow_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_startEvaluatorShadow_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":101,"column":3},
    },
    {
      id: 'dsh-evolve#evoforgeEvolution/startFeedbackShadow',
      service: 'evoforge.evolutionControl',
      namespace: 'evoforgeEvolution',
      method: 'startFeedbackShadow',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'signalId',
          wire: 'signalId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/startFeedbackShadow:signalId',
            schema: dsh_evolve_evoforgeEvolution_startFeedbackShadow_parameter_0$schema,
          },
        },
        {
          name: 'targetId',
          wire: 'targetId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-evolve#evoforgeEvolution/startFeedbackShadow:targetId',
            schema: dsh_evolve_evoforgeEvolution_startFeedbackShadow_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-evolve/client#EvolutionActionReceipt',
        schema: dsh_evolve_evoforgeEvolution_startFeedbackShadow_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-evolve/src/evolution-remote.typert.ts","line":67,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "evoforge.evolution",
        "exportName": "EvolutionStore",
        "members": [
          {
            "kind": "method",
            "name": "publishGeneration",
            "signature": "publishGeneration(input: GenerationInput): Promise<{ created: boolean generation: CapabilityGeneration }>"
          },
          {
            "kind": "method",
            "name": "getGeneration",
            "signature": "getGeneration(id: string): CapabilityGeneration | undefined"
          },
          {
            "kind": "method",
            "name": "getActiveGeneration",
            "signature": "getActiveGeneration(): CapabilityGeneration | undefined"
          },
          {
            "kind": "method",
            "name": "promoteGeneration",
            "signature": "promoteGeneration(id: string): Promise<{ previousId: string | undefined generation: CapabilityGeneration }>"
          },
          {
            "kind": "method",
            "name": "rollbackGeneration",
            "signature": "rollbackGeneration(): Promise<{ previousId: string generation: CapabilityGeneration | undefined }>"
          },
          {
            "kind": "method",
            "name": "pinSession",
            "signature": "pinSession( identity: SessionIdentity, options?: { parentSessionId?: string }, ): Promise<CapabilityGeneration | undefined>"
          },
          {
            "kind": "method",
            "name": "fallbackSessionToNative",
            "signature": "fallbackSessionToNative(identity: SessionIdentity): Promise<void>"
          },
          {
            "kind": "method",
            "name": "getSessionGeneration",
            "signature": "getSessionGeneration(identity: SessionIdentity): CapabilityGeneration | undefined"
          },
          {
            "kind": "method",
            "name": "isRecoveryPaused",
            "signature": "isRecoveryPaused(): boolean"
          },
          {
            "kind": "method",
            "name": "setRecoveryPaused",
            "signature": "setRecoveryPaused(paused: boolean): Promise<{ changed: boolean; paused: boolean }>"
          },
          {
            "kind": "method",
            "name": "close",
            "signature": "close(): Promise<void>"
          }
        ],
        "types": [
          {
            "name": "CapabilityGeneration",
            "declaration": "export interface CapabilityGeneration extends GenerationInput {\n    id: string;\n    schemaVersion: 1;\n}"
          },
          {
            "name": "GenerationInput",
            "declaration": "export interface GenerationInput {\n    parentId?: string | undefined;\n    createdAt: number;\n    artifacts: SkillGenerationArtifact[];\n    evaluatorVersion: string;\n    policyVersion: string;\n    compositionFingerprint: string;\n}"
          },
          {
            "name": "SessionIdentity",
            "declaration": "export interface SessionIdentity {\n    sessionId: string;\n    createdAt: number;\n    cwd?: string | undefined;\n}"
          },
          {
            "name": "SkillGenerationArtifact",
            "declaration": "export interface SkillGenerationArtifact {\n    kind: 'skill';\n    name: string;\n    gitCommit: string;\n    treeHash: string;\n}"
          }
        ]
      },
      {
        "description": "Generated-Remote transport adapter; all policy and state remain in EvolutionControlPlane.",
        "summary": "Generated-Remote transport adapter; all policy and state remain in EvolutionControlPlane.",
        "tags": [],
        "jsDoc": "/** Generated-Remote transport adapter; all policy and state remain in EvolutionControlPlane. */",
        "key": "evoforge.evolutionControl",
        "exportName": "EvolutionRemoteService",
        "members": [
          {
            "kind": "method",
            "name": "overview",
            "signature": "overview(): Promise<EvolutionOverview>"
          },
          {
            "kind": "method",
            "name": "review",
            "signature": "review(id: string): Promise<EvolutionReviewDetail>"
          },
          {
            "kind": "method",
            "name": "pause",
            "signature": "pause(): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "resume",
            "signature": "resume(): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "approveReview",
            "signature": "approveReview(id: string, note: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "rejectReview",
            "signature": "rejectReview(id: string, note: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "promote",
            "signature": "promote(generationId: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "rollback",
            "signature": "rollback(): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "startFeedbackShadow",
            "signature": "startFeedbackShadow(signalId: string, targetId: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "evaluatorDraft",
            "signature": "evaluatorDraft(id: string): Promise<EvolutionEvaluatorDraftDetail>"
          },
          {
            "kind": "method",
            "name": "authorEvaluator",
            "signature": "authorEvaluator(signalId: string, targetId: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "approveEvaluator",
            "signature": "approveEvaluator(id: string, note: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "rejectEvaluator",
            "signature": "rejectEvaluator(id: string, note: string): Promise<EvolutionActionReceipt>"
          },
          {
            "kind": "method",
            "name": "startEvaluatorShadow",
            "signature": "startEvaluatorShadow(id: string): Promise<EvolutionActionReceipt>"
          }
        ],
        "types": [
          {
            "name": "CandidateImpactIndicator",
            "declaration": "export type CandidateImpactIndicator = 'artifact-scope-change' | 'credential-access' | 'destructive-action' | 'messaging-or-calendar' | 'network-access' | 'payment-action' | 'permission-or-sandbox' | 'privileged-tooling' | 'production-change' | 'rewritten-instructions';"
          },
          {
            "name": "CandidateImpactProjection",
            "declaration": "export interface CandidateImpactProjection {\n    readonly version: 'lexical-protected-effects-v1';\n    readonly scope: 'append-only-skill' | 'broader-change';\n    readonly indicators: readonly CandidateImpactIndicator[];\n}"
          },
          {
            "name": "DeliveryOutcomeCounts",
            "declaration": "export interface DeliveryOutcomeCounts {\n    readonly total: number;\n    readonly passed: number;\n    readonly failed: number;\n    readonly unknown: number;\n}"
          },
          {
            "name": "EvolutionActionReceipt",
            "declaration": "export interface EvolutionActionReceipt {\n    readonly schemaVersion: 1;\n    readonly action: 'pause' | 'resume' | 'approve-review' | 'reject-review' | 'promote' | 'rollback' | 'start-shadow' | 'author-evaluator' | 'approve-evaluator' | 'reject-evaluator';\n    readonly reviewId?: string;\n    readonly status?: 'approved' | 'rejected';\n    readonly generationId?: string;\n    readonly previousGenerationId?: string;\n    readonly activeGenerationId?: string;\n    readonly recoveryPaused?: boolean;\n    readonly launchId?: string;\n    readonly targetId?: string;\n    readonly skillName?: string;\n    readonly runStatus?: 'scheduled' | 'prepared' | 'proposal-pending' | 'candidate-ready' | 'trial-running' | 'complete' | 'incomplete';\n    readonly jobId?: string;\n    readonly draftId?: string;\n    readonly draftStatus?: 'scheduled' | 'authoring-pending' | 'uncertain' | 'draft-ready' | 'qualification-running' | 'qualified' | 'incomplete' | 'rejected';\n}"
          },
          {
            "name": "EvolutionArtifactView",
            "declaration": "export interface EvolutionArtifactView {\n    readonly kind: 'skill';\n    readonly name: string;\n    readonly gitCommit: string;\n    readonly treeHash: string;\n}"
          },
          {
            "name": "EvolutionAutomaticBudgetView",
            "declaration": "export interface EvolutionAutomaticBudgetView {\n    readonly targetId: string;\n    readonly skillName: string;\n    readonly utcDay: string;\n    readonly used: number;\n    readonly limit: number;\n    readonly remaining: number;\n    readonly status: 'ready' | 'unknown';\n}"
          },
          {
            "name": "EvolutionEvaluatorDraftDetail",
            "declaration": "export interface EvolutionEvaluatorDraftDetail {\n    readonly schemaVersion: 1;\n    readonly draft: EvolutionEvaluatorDraftView;\n    readonly files: readonly { readonly path: string; readonly content: string; }[];\n    readonly limitations: readonly string[];\n    readonly qualifiedShadowAvailable: boolean;\n    readonly decision?: { readonly actor: 'human'; readonly note: string; readonly decidedAt: string; };\n    readonly qualification?: { readonly calibrated: boolean; readonly attempt: number; };\n    readonly reason?: string;\n}"
          },
          {
            "name": "EvolutionEvaluatorDraftView",
            "declaration": "export interface EvolutionEvaluatorDraftView {\n    readonly id: string;\n    readonly launchId: string;\n    readonly targetId: string;\n    readonly skillName: string;\n    readonly status: 'authoring-pending' | 'uncertain' | 'draft-ready' | 'qualification-running' | 'qualified' | 'incomplete' | 'rejected';\n    readonly createdAt: string;\n    readonly updatedAt: string;\n    readonly cost: { readonly modelCalls: 0 | 1; readonly inputTokens: number; readonly outputTokens: number; };\n}"
          },
          {
            "name": "EvolutionFeedbackSignalView",
            "declaration": "export interface EvolutionFeedbackSignalView {\n    readonly id: string;\n    readonly sourceUpdatedAt: number;\n    readonly generationId?: string;\n}"
          },
          {
            "name": "EvolutionGenerationView",
            "declaration": "export interface EvolutionGenerationView {\n    readonly id: string;\n    readonly rollbackTargetId?: string;\n    readonly createdAt: number;\n    readonly evaluatorVersion: string;\n    readonly policyVersion: string;\n    readonly artifacts: readonly EvolutionArtifactView[];\n}"
          },
          {
            "name": "EvolutionInactiveGenerationView",
            "declaration": "export interface EvolutionInactiveGenerationView {\n    readonly generationId: string;\n    readonly reviewId: string;\n    readonly skillName: string;\n}"
          },
          {
            "name": "EvolutionOverview",
            "declaration": "export interface EvolutionOverview {\n    readonly schemaVersion: 1;\n    readonly active?: EvolutionGenerationView;\n    readonly recovery: { readonly available: boolean; readonly paused?: boolean; };\n    readonly automaticPromotion: { readonly enabled: boolean; readonly skills: readonly string[]; };\n    readonly deliveryOutcomes?: { readonly all: DeliveryOutcomeCounts; readonly selected: DeliveryOutcomeCounts; };\n    readonly feedbackSignals?: { readonly all: number; readonly selected: number; };\n    readonly feedbackShadow?: { readonly available: boolean; readonly warningCount: number; readonly signals: readonly EvolutionFeedbackSignalView[]; readonly targets: readonly EvolutionShadowTargetView[]; readonly runs: readonly EvolutionShadowRunView[]; };\n    readonly automaticFeedbackBudget?: { readonly warningCount: number; readonly targets: readonly EvolutionAutomaticBudgetView[]; };\n    readonly evaluatorAuthoring?: { readonly available: boolean; readonly warningCount: number; readonly signals: readonly EvolutionFeedbackSignalView[]; readonly targets: readonly EvolutionShadowTargetView[]; readonly drafts: readonly EvolutionEvaluatorDraftView[]; };\n    readonly reviews: { readonly available: boolean; readonly pendingCount: number; readonly actionableCount: number; readonly warningCount: number; readonly items: readonly EvolutionReviewView[]; readonly inactiveGenerations: readonly EvolutionInactiveGenerationView[]; };\n}"
          },
          {
            "name": "EvolutionReviewCaseView",
            "declaration": "export interface EvolutionReviewCaseView {\n    readonly id: string;\n    readonly baseline: 'pass' | 'fail' | 'incomplete';\n    readonly candidate: 'pass' | 'fail' | 'incomplete';\n    readonly passedChecks: number;\n    readonly totalChecks: number;\n}"
          },
          {
            "name": "EvolutionReviewDetail",
            "declaration": "export interface EvolutionReviewDetail {\n    readonly schemaVersion: 1;\n    readonly review: EvolutionReviewView;\n    readonly diff: { readonly patch: string; readonly shownBytes: number; readonly totalBytes: number; readonly truncated: boolean; readonly impact: CandidateImpactProjection; };\n    readonly automatic?: { readonly eligible: boolean; readonly policyVersion: 'auto-clear-instruction-v1'; readonly reasons: readonly string[]; };\n}"
          },
          {
            "name": "EvolutionReviewView",
            "declaration": "export interface EvolutionReviewView {\n    readonly id: string;\n    readonly status: 'pending' | 'approved' | 'rejected';\n    readonly recommendation: 'promote' | 'review';\n    readonly skillName: string;\n    readonly claim: string;\n    readonly changedFiles: readonly string[];\n    readonly candidateTreeHash: string;\n    readonly cases: readonly EvolutionReviewCaseView[];\n    readonly cost: { readonly inputTokens: number; readonly outputTokens: number; readonly trialCount: number; };\n    readonly reasons: readonly string[];\n    readonly limitations: readonly string[];\n    readonly evaluatorVersion: string;\n    readonly compositionFingerprint: string;\n    readonly compositionStable: boolean;\n    readonly startedAt: string;\n    readonly decisionActor?: 'human' | 'auto-clear-instruction-v1';\n    readonly decisionNote?: string;\n    readonly generationId?: string;\n    readonly activatedAt?: string;\n}"
          },
          {
            "name": "EvolutionShadowRunView",
            "declaration": "export interface EvolutionShadowRunView {\n    readonly launchId: string;\n    readonly targetId: string;\n    readonly skillName: string;\n    readonly phase: 'prepared' | 'proposal-pending' | 'candidate-ready' | 'trial-running' | 'complete' | 'incomplete';\n    readonly startedAt: string;\n    readonly updatedAt: string;\n}"
          },
          {
            "name": "EvolutionShadowTargetView",
            "declaration": "export interface EvolutionShadowTargetView {\n    readonly id: string;\n    readonly skillName: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
