export const STYLE_ID = 'dsh-control-center-v1'

export const cssText = `
.dsh-cc-root{height:100%;min-height:0;overflow:auto;background:var(--dsw-alias-bg-base,#f7f8fa);color:var(--dsw-alias-label-primary,#1f2329)}
.dsh-cc-shell{display:grid;grid-template-columns:224px minmax(0,1fr);min-height:100%;isolation:isolate}
.dsh-cc-nav{position:sticky;top:0;display:flex;box-sizing:border-box;flex-direction:column;height:100%;min-height:560px;padding:28px 18px 22px;border-right:1px solid var(--dsw-alias-border-l1,#e7e9ed);background:color-mix(in srgb,var(--dsw-specific-sidebar-fill,#f7f8fa) 86%,transparent)}
.dsh-cc-brand{display:flex;align-items:center;gap:11px}.dsh-cc-brand-mark{display:grid;width:34px;height:34px;border-radius:11px;background:#2563eb;color:white;font-weight:760;place-items:center;box-shadow:0 7px 20px #2563eb2b}.dsh-cc-brand div{display:grid;gap:1px}.dsh-cc-brand div span{font-size:9px;font-weight:760;letter-spacing:.14em;color:var(--dsw-alias-label-tertiary,#8b919c)}.dsh-cc-brand strong{font-size:15px;letter-spacing:-.01em}
.dsh-cc-nav-description{margin:14px 0 26px;color:var(--dsw-alias-label-secondary,#646a73);font-size:12px;line-height:1.55}.dsh-cc-nav-label{margin:0 8px 8px;color:var(--dsw-alias-label-tertiary,#8b919c);font-size:10px;font-weight:680;letter-spacing:.08em}
.dsh-cc-nav-items{display:grid;gap:3px}.dsh-cc-nav-items button{display:grid;grid-template-columns:28px 1fr;align-items:center;width:100%;padding:10px 9px;border:0;border-radius:10px;background:transparent;color:var(--dsw-alias-label-secondary,#646a73);font:inherit;font-size:13px;text-align:left;cursor:pointer;transition:background .15s ease,color .15s ease}.dsh-cc-nav-items button:hover{background:color-mix(in srgb,currentColor 7%,transparent);color:var(--dsw-alias-label-primary,#1f2329)}.dsh-cc-nav-items button.is-active{background:var(--dsw-alias-button-secondary-fill,#fff);color:var(--dsw-alias-label-primary,#1f2329);box-shadow:inset 0 0 0 1px var(--dsw-alias-border-l2,#dfe1e5),0 3px 12px #0000000a}.dsh-cc-nav-index{color:var(--dsw-alias-label-tertiary,#8b919c);font:600 9px/1 ui-monospace,SFMono-Regular,Menlo,monospace}.dsh-cc-nav-items button.is-active .dsh-cc-nav-index{color:#2563eb}
.dsh-cc-authority{display:flex;align-items:center;gap:7px;margin:auto 7px 0;color:var(--dsw-alias-label-tertiary,#8b919c);font-size:10px}.dsh-cc-authority>span{width:6px;height:6px;border-radius:50%;background:#16a34a;box-shadow:0 0 0 3px #16a34a1c}
.dsh-cc-stage{min-width:0}.dsh-cc-surface{box-sizing:border-box;display:grid;gap:18px;width:min(1080px,100%);margin:0 auto;padding:34px 38px 48px}
.dsh-cc-surface-head{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;padding:24px 26px;border:1px solid var(--dsw-alias-border-l2,#dfe1e5);border-radius:20px;background:linear-gradient(135deg,color-mix(in srgb,#2563eb 5%,var(--dsw-specific-menu,#fff)),var(--dsw-specific-menu,#fff) 56%);box-shadow:0 10px 35px #00000008}.dsh-cc-surface-copy{min-width:0}.dsh-cc-eyebrow{display:block;margin-bottom:8px;color:#2563eb;font-size:10px;font-weight:760;letter-spacing:.12em}.dsh-cc-title-line{display:flex;align-items:center;flex-wrap:wrap;gap:10px}.dsh-cc-title-line h2{margin:0;font-size:24px;line-height:1.2;letter-spacing:-.025em}.dsh-cc-surface-copy>p{max-width:680px;margin:8px 0 0;color:var(--dsw-alias-label-secondary,#646a73);font-size:13px;line-height:1.55}.dsh-cc-head-actions{display:flex;flex:none;gap:8px}
.dsh-cc-status{display:inline-flex;align-items:center;gap:6px;width:max-content;padding:4px 8px;border-radius:999px;background:color-mix(in srgb,currentColor 10%,transparent);font-size:10px;font-weight:700;white-space:nowrap}.dsh-cc-status>span{width:6px;height:6px;border-radius:50%;background:currentColor}.dsh-cc-status.is-healthy{color:#16845b}.dsh-cc-status.is-working{color:#2563eb}.dsh-cc-status.is-attention{color:#b66b06}.dsh-cc-status.is-danger{color:#c43b43}.dsh-cc-status.is-neutral{color:var(--dsw-alias-label-secondary,#646a73)}
.dsh-cc-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:0}.dsh-cc-metrics>div{min-width:0;padding:15px 16px;border:1px solid var(--dsw-alias-border-l2,#dfe1e5);border-radius:14px;background:var(--dsw-specific-menu,#fff)}.dsh-cc-metrics dt{color:var(--dsw-alias-label-secondary,#646a73);font-size:11px}.dsh-cc-metrics dd{margin:7px 0 0;font-size:22px;font-weight:720;line-height:1;letter-spacing:-.025em}.dsh-cc-metrics small{display:block;margin-top:7px;color:var(--dsw-alias-label-tertiary,#8b919c);font-size:10px}.dsh-cc-metrics>div.is-danger dd{color:#c43b43}.dsh-cc-metrics>div.is-attention dd{color:#b66b06}.dsh-cc-metrics>div.is-healthy dd{color:#16845b}
.dsh-cc-card{overflow:hidden;border:1px solid var(--dsw-alias-border-l2,#dfe1e5);border-radius:16px;background:var(--dsw-specific-menu,#fff)}.dsh-cc-card-head{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:17px 19px;border-bottom:1px solid var(--dsw-alias-border-l1,#e7e9ed)}.dsh-cc-card-head h3{margin:0;font-size:14px;letter-spacing:-.01em}.dsh-cc-card-head p{margin:4px 0 0;color:var(--dsw-alias-label-secondary,#646a73);font-size:11px;line-height:1.45}.dsh-cc-card-body{display:grid}
.dsh-cc-entity{display:grid;grid-template-columns:auto minmax(0,1fr) auto auto;align-items:center;gap:12px;min-height:54px;padding:12px 18px}.dsh-cc-entity+.dsh-cc-entity{border-top:1px solid var(--dsw-alias-border-l1,#e7e9ed)}.dsh-cc-entity-icon{display:grid;width:32px;height:32px;border-radius:10px;background:color-mix(in srgb,#2563eb 8%,transparent);color:#2563eb;place-items:center;font-size:14px;font-weight:700}.dsh-cc-entity-copy{display:grid;min-width:0;gap:3px}.dsh-cc-entity-copy strong{overflow:hidden;font-size:12px;text-overflow:ellipsis;white-space:nowrap}.dsh-cc-entity-copy>span{color:var(--dsw-alias-label-secondary,#646a73);font-size:10px;line-height:1.4}.dsh-cc-entity-copy details{margin-top:3px;color:var(--dsw-alias-label-tertiary,#8b919c);font-size:10px}.dsh-cc-entity-copy summary{cursor:pointer}.dsh-cc-entity-copy code{overflow-wrap:anywhere;font-size:9px}.dsh-cc-entity-status,.dsh-cc-entity-actions{display:flex;gap:7px;align-items:center}
.dsh-cc-notice{display:flex;align-items:flex-start;gap:8px;padding:11px 13px;border:1px solid color-mix(in srgb,currentColor 18%,transparent);border-radius:12px;background:color-mix(in srgb,currentColor 6%,transparent);color:var(--dsw-alias-label-secondary,#646a73);font-size:11px;line-height:1.5}.dsh-cc-notice strong{color:var(--dsw-alias-label-primary,#1f2329);white-space:nowrap}.dsh-cc-notice.is-healthy{color:#16845b}.dsh-cc-notice.is-working{color:#2563eb}.dsh-cc-notice.is-attention{color:#a55f02}.dsh-cc-notice.is-danger{color:#b8323b}
.dsh-cc-button{min-height:32px;padding:6px 11px;border:1px solid var(--dsw-alias-border-l2,#dfe1e5);border-radius:9px;background:var(--dsw-alias-button-secondary-fill,#fff);color:var(--dsw-alias-label-primary,#1f2329);font:inherit;font-size:11px;font-weight:620;cursor:pointer}.dsh-cc-button:hover{background:var(--dsw-alias-button-secondary-hover,#f3f4f6)}.dsh-cc-button.is-primary{border-color:#2563eb;background:#2563eb;color:#fff}.dsh-cc-button.is-primary:hover{background:#1d4ed8}.dsh-cc-button.is-danger{border-color:#dc262644;background:#dc262610;color:#c43b43}.dsh-cc-button:disabled{cursor:not-allowed;opacity:.5}.dsh-cc-button:focus-visible,.dsh-cc-nav-items button:focus-visible{outline:2px solid #2563eb;outline-offset:2px}
.dsh-cc-empty-state{display:grid;align-content:center;gap:2px;min-height:100%;padding:28px 38px 48px}.dsh-cc-empty{display:grid;min-height:250px;padding:24px 40px 18px;text-align:center;place-content:center}.dsh-cc-empty>span{font-size:30px;color:var(--dsw-alias-label-tertiary,#8b919c)}.dsh-cc-empty h2{margin:14px 0 0;font-size:18px}.dsh-cc-empty p{max-width:420px;margin:8px auto 0;color:var(--dsw-alias-label-secondary,#646a73);font-size:12px;line-height:1.5}.dsh-cc-empty-guide{width:min(760px,100%);margin:0 auto;padding:18px 20px;border:1px solid var(--dsw-alias-border-l2,#dfe1e5);border-radius:16px;background:var(--dsw-specific-menu,#fff);box-shadow:0 8px 28px #00000006}.dsh-cc-empty-guide-head{display:flex;align-items:baseline;justify-content:space-between;gap:12px}.dsh-cc-empty-guide-head span{color:#2563eb;font-size:10px;font-weight:760;letter-spacing:.1em;text-transform:uppercase}.dsh-cc-empty-guide-head strong{font-size:13px}.dsh-cc-empty-suite-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:12px}.dsh-cc-empty-suite{min-width:0;padding:11px 12px;border-radius:11px;background:var(--dsw-alias-fill-l1,#f7f8fa)}.dsh-cc-empty-suite-key{color:#2563eb;font:700 11px ui-monospace,SFMono-Regular,Menlo,monospace}.dsh-cc-empty-suite p{margin:5px 0 0;color:var(--dsw-alias-label-secondary,#646a73);font-size:10px;line-height:1.45}.dsh-cc-empty-note{margin:12px 0 0;color:var(--dsw-alias-label-tertiary,#8b919c);font-size:10px;line-height:1.45}
.dsh-cc-loading{display:grid;gap:14px;padding:34px 38px}.dsh-cc-skeleton{height:120px;border-radius:16px;background:linear-gradient(90deg,color-mix(in srgb,currentColor 5%,transparent),color-mix(in srgb,currentColor 10%,transparent),color-mix(in srgb,currentColor 5%,transparent));background-size:220% 100%;animation:dsh-cc-shimmer 1.6s ease-in-out infinite}.dsh-cc-skeleton.is-head{height:150px}.dsh-cc-skeleton-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}
.dsh-cc-journey{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:0;margin:0;padding:0;list-style:none}.dsh-cc-journey li{position:relative;display:grid;grid-template-columns:30px minmax(0,1fr);align-items:start;gap:10px;padding:16px 18px}.dsh-cc-journey li+li{border-left:1px solid var(--dsw-alias-border-l1,#e7e9ed)}.dsh-cc-journey-mark{display:grid;width:26px;height:26px;border:1px solid var(--dsw-alias-border-l2,#dfe1e5);border-radius:50%;background:var(--dsw-alias-bg-base,#f7f8fa);color:var(--dsw-alias-label-tertiary,#8b919c);font:700 10px/1 ui-monospace,SFMono-Regular,Menlo,monospace;place-items:center}.dsh-cc-journey-copy{display:grid;gap:4px}.dsh-cc-journey-copy strong{font-size:11px}.dsh-cc-journey-copy small{color:var(--dsw-alias-label-secondary,#646a73);font-size:10px;line-height:1.45}.dsh-cc-journey li.is-complete .dsh-cc-journey-mark{border-color:#16a34a36;background:#16a34a12;color:#16845b}.dsh-cc-journey li.is-current{background:color-mix(in srgb,#2563eb 4%,transparent)}.dsh-cc-journey li.is-current .dsh-cc-journey-mark{border-color:#2563eb;background:#2563eb;color:#fff;box-shadow:0 0 0 3px #2563eb18}.dsh-cc-journey li.is-attention{background:color-mix(in srgb,#c43b43 4%,transparent)}.dsh-cc-journey li.is-attention .dsh-cc-journey-mark{border-color:#c43b4345;background:#c43b4310;color:#c43b43}
.dsh-cc-form{display:grid;gap:9px;padding:16px 18px}.dsh-cc-form label{font-size:11px;font-weight:650}.dsh-cc-form p{margin:0;color:var(--dsw-alias-label-secondary,#646a73);font-size:10px;line-height:1.5}.dsh-cc-form-row{display:flex;gap:8px}.dsh-cc-form input{min-width:0;flex:1;height:34px;box-sizing:border-box;padding:7px 10px;border:1px solid var(--dsw-alias-border-l2,#dfe1e5);border-radius:9px;background:var(--dsw-alias-bg-base,#f7f8fa);color:inherit;font:600 12px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.1em;text-transform:uppercase}.dsh-cc-form input:focus{border-color:#2563eb;outline:2px solid #2563eb20}
.dsh-cc-permissions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0}.dsh-cc-permissions>div{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 18px;border-bottom:1px solid var(--dsw-alias-border-l1,#e7e9ed);font-size:11px}.dsh-cc-permissions>div:nth-child(odd){border-right:1px solid var(--dsw-alias-border-l1,#e7e9ed)}.dsh-cc-permissions strong{font-size:10px}.dsh-cc-permissions strong.is-enabled{color:#16845b}.dsh-cc-permissions strong.is-disabled{color:var(--dsw-alias-label-tertiary,#8b919c)}
@keyframes dsh-cc-shimmer{0%{background-position:100% 0}100%{background-position:-100% 0}}
@media(max-width:900px){.dsh-cc-shell{grid-template-columns:1fr}.dsh-cc-nav{position:relative;z-index:1;height:auto;min-height:0;padding:16px 20px;border-right:0;border-bottom:1px solid var(--dsw-alias-border-l1,#e7e9ed)}.dsh-cc-brand,.dsh-cc-nav-description,.dsh-cc-nav-label,.dsh-cc-authority{display:none}.dsh-cc-nav-items{display:flex;overflow:auto}.dsh-cc-nav-items button{display:flex;width:auto;min-width:max-content;padding:8px 11px}.dsh-cc-surface{padding:24px 22px 40px}}
@media(max-width:640px){.dsh-cc-surface{gap:12px;padding:16px 12px 30px}.dsh-cc-empty-state{padding:14px 12px 30px}.dsh-cc-empty{min-height:230px;padding:20px 12px 14px}.dsh-cc-empty-guide{padding:15px}.dsh-cc-empty-guide-head{display:grid;gap:4px}.dsh-cc-empty-suite-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.dsh-cc-surface-head{display:grid;padding:19px;border-radius:15px}.dsh-cc-title-line h2{font-size:20px}.dsh-cc-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.dsh-cc-entity{grid-template-columns:auto minmax(0,1fr) auto}.dsh-cc-entity-actions{grid-column:2/-1}.dsh-cc-permissions{grid-template-columns:1fr}.dsh-cc-permissions>div:nth-child(odd){border-right:0}.dsh-cc-skeleton-grid{grid-template-columns:1fr}.dsh-cc-journey{grid-template-columns:1fr}.dsh-cc-journey li+li{border-top:1px solid var(--dsw-alias-border-l1,#e7e9ed);border-left:0}.dsh-cc-form-row{display:grid}}
@media(prefers-reduced-motion:reduce){.dsh-cc-skeleton{animation:none}.dsh-cc-nav-items button{transition:none}}
`
